### ISSUE TITLE
Prevent local "Ignore beatmap skin" from affecting the editor

### ISSUE THREAD

**Issue by Uberzolik** [ppy/osu-stable-issues#114] opened 2019-09-25 20:52 UTC
By "local", I'm referring to this setting within the map itself: 

![screenshot5527](https://user-images.githubusercontent.com/12388394/65638577-c85e9c00-dfbc-11e9-8c3c-9fb3556f53fb.png)

There's no real reason this should affect the map within the editor, and I often find myself annoyed by the fact the setting seems to have gotten "stuck" enabled on certain maps, where it erroneously saved me using the "Ignore all beatmap skins" option, thus not displaying the combo colors when I disable the global option, as it locally stored the ignore within the map.

Easiest solution would be to simply make the setting not affect the editor, only ingame.

**Comment by peppy** [comment] 2019-09-26 00:32
Is it safe to say that people never want a beatmap skin to disable in the editor? I think this sounds fair.

**Comment by Uberzolik** [comment] 2019-09-26 01:03
It should be fine as long as "Ignore all beatmap skins" still disables the map's skin, I don't think anyone actually goes into the map to manually disable the skin like this.

**Comment by smoogipoo** [comment] 2019-09-26 02:09
Duplicate of https://github.com/ppy/osu-stable-issues/issues/49, will be resolved by the same fix.

**Closed by smoogipoo** 2019-09-26 02:09 UTC
Labels: easy fix

**Comment by Uberzolik** [comment] 2019-09-26 02:11
Wasn't really the same thing, since I believe he was referring to the "Ignore all beatmap skins" option, while I was referring to the local one... but it might fix it anyway, so thanks anyhow!

**Comment by Uberzolik** [comment] 2019-12-15 17:31
Would it be possible to reopen this since #49 was determined to be too out of scope? This seems like a simpler fix.
