### ISSUE TITLE
Editor is black on Nvidia v430+ drivers

### ISSUE THREAD

**Issue by Devocub** [ppy/osu-stable-issues#207] opened 2019-11-06 11:17 UTC
win10 x64 1903 and 1909
Any Nvidia driver with version higher than 425.x have black screen when you enter osu! editor from osu! exclusive fullscreen. You need to restart osu! to get any picture back. However if osu! is captured by OBS you can see what happens in game trough OBS but main screen still remains black.

https://www.nvidia.com/Download/Find.aspx
![image](https://user-images.githubusercontent.com/2735824/68293716-97838380-009f-11ea-9357-35a904cc1621.png)

**Comment by peppy** [comment] 2019-11-06 14:43
436.30 here, works fine.

**Comment by Syntractrix** [comment] 2019-11-06 17:14
I think this developer is brain dead and should try to install any other version of 10 besides the newest one. He should also try w7 :)

**Comment by Devocub** [comment] 2019-11-06 17:26
That happens only if i have 2 monitors active and my main screen is 2nd and placed after first one

Editor is black
![image](https://user-images.githubusercontent.com/2735824/68321869-818fb600-00d3-11ea-987f-08d96ca0f60c.png)

This combination works well, everything is ok (441.12 nvidia driver)
![image](https://user-images.githubusercontent.com/2735824/68321959-9e2bee00-00d3-11ea-9323-7a8d70121e62.png)

**Comment by Syntractrix** [comment] 2019-11-06 17:32
this specific issue wouldn't even happen if you used w7

**Comment by ThePooN** [comment] 2019-11-06 18:10
@Syntractrix This place is for constructive discussion.

**Comment by l3lackShark** [comment] 2019-11-12 14:49
Can confirm having the exact same issue, 
441.20 Driver

**Comment by peppy** [comment] 2019-11-13 05:23
Can you also confirm this only happens with multiple displays?

**Comment by l3lackShark** [comment] 2019-11-13 05:39
For me, the issue is a little bit different when it comes to multiple displays.

**Chain of reproduction1**: open osu! >> put it into the window mode >> move to another display, fullscreen it. (Editor is black)

**Chain of reproduction2**: open osu! on main monitor with non-native resolution fullscreen (Editor is black)

**Comment by DatVeno** [comment] 2019-11-16 09:21
@peppy I have the exact same problem after updating my graphics driver for a long time. Seems like people with 2 monitors and different resolutions get that blackscreen after osu goes from fullscreen to windowed.

**Comment by Touconan** [comment] 2019-11-17 08:14
Still happening on 411.12, probably going to reinstall windows in the next week or so, will update if that fixes it.

**Comment by DatVeno** [comment] 2019-11-19 16:26
@Touconan just upgraded from windows 8.1 to windows 10 recently, and had the problem on both.

**Comment by DatVeno** [comment] 2019-11-19 17:38
@peppy Even switching from fullscreen to windowed in the settings will cause this blackscreen bug.

**Comment by Devocub** [comment] 2019-11-19 17:43
@DatVeno exclusive fullscreen -> borderless fullscreen (aka window)
it doesn't happen in other games (just checked in game SOMA)

**Comment by DatVeno** [comment] 2019-11-19 17:48
this also doesn't happen in lazer btw and yeah it only happens when switching from fullscreen to borderless windowed

**Comment by itzpigeon** [comment] 2019-11-21 02:13
I made a forum post just a bit earlier today with this same issue since I'd never seen this before: https://osu.ppy.sh/community/forums/topics/987965 
I can at least confirm that I have a dual monitor setup where my primary monitor is labeled as '2' and my secondary monitor is labeled as '1'. I only started having this issue since about last week, but it had been a while since I'd opened up the editor.
I'm running version 432.00, which I don't see on the list already made. :/

**Comment by mojobojo** [comment] 2019-11-30 12:25
I can confirm this can happen on a main monitor that is set to 1 as well. This is my current setup on 441.41

![image](https://i.imgur.com/Qzxd9vW.png)

**Comment by Touconan** [comment] 2019-12-01 19:01
Reinstalled Windows 10 and osu!, can confirm that the issue still persists.

![image](https://user-images.githubusercontent.com/49025619/69918662-ed392900-14af-11ea-9bb0-801c6d7e039d.png)
The two monitors on the left are both 1600x900, and the main is 1920x1080

**Comment by Mokobe-osu** [comment] 2019-12-18 12:45
The issue is also prominent with two 1080p displays.

RX570 here.

I am able to reproduce the issue at will, just by opening editor.

**Comment by peppy** [comment] 2019-12-23 01:43
Could anyone with this issue please post their `runtime.log` after reproducing the issue?

**Comment by Devocub** [comment] 2019-12-23 02:21
[runtime.log](https://github.com/ppy/osu-stable-issues/files/3993406/runtime.log)

**Comment by DatVeno** [comment] 2019-12-23 13:03
[runtime.log](https://github.com/ppy/osu-stable-issues/files/3995036/runtime.log)

**Comment by DatVeno** [comment] 2019-12-23 13:31
[Here a video just so you can see how it looks for us](https://streamable.com/olmr6)

The second try where the editor didn't go black was when I unplugged my second monitor.

**Comment by stanriders** [comment] 2019-12-25 14:53
You can also fix rendering after that by going back to the main menu and pressing win key. 
I'm using two monitors with different resolutions (2k and 1080p), fullscreen letterboxing, game stops rendering as soon as it goes into editor song select (regular song select works fine). If i go into windowed mode editor works as expected

**Comment by RealistikDash** [comment] 2020-01-23 22:47
Here with the same issue willing to chip in. You interact with the game just fine and even take screenshots which works as if the screen wasn't black.

**Comment by peppy** [comment] 2020-03-12 15:36
I've been trying to reproduce this to no avail.

![image](https://user-images.githubusercontent.com/191335/76538375-8f5ea900-64c2-11ea-9bd7-5793fd1e485f.png)

![image](https://user-images.githubusercontent.com/191335/76538394-971e4d80-64c2-11ea-8546-623e4bc0c56d.png)

am i missing something?

**Comment by RealistikDash** [comment] 2020-03-13 21:12
My config (where it occurs)
![image](https://user-images.githubusercontent.com/36131887/76659760-8ed41a00-6577-11ea-93bd-4bda4e351a24.png)
![image](https://user-images.githubusercontent.com/36131887/76659776-985d8200-6577-11ea-9b15-9bf83bb551c6.png)

**Comment by stanriders** [comment] 2020-03-13 21:19
My setup
![image](https://user-images.githubusercontent.com/8269193/76659980-e62eb600-6588-11ea-951f-4e61b87e6598.png)

Fullscreen letterboxed, primary 144hz, secondary 60hz, game runs on primary

**Comment by peppy** [comment] 2020-03-14 03:16
can you guys please first update drivers to latest (same or beyond my version)?

i cannot repro with any of the posted layouts.

**Comment by RealistikDash** [comment] 2020-03-14 11:45
![image](https://user-images.githubusercontent.com/36131887/76681267-86202a00-65f1-11ea-9f0d-7ecfffb5276f.png)
Still occurs after updating.

I am unaware if this will help but I also, just like @stanriders have different refresh rates (144hz on primary, 75hz on secondary). I think this issue might boil down to that.

**Comment by peppy** [comment] 2020-03-14 12:39
In my test my primary was 165, secondary 60.

**Comment by RealistikDash** [comment] 2020-03-23 17:09
Then I am unaware of what is directly causing the issue.  I will keep on testing to pinpoint the issue. So far I've discovered that turning off a monitor/setting it to mirror displays gets rid of the issue. As soon as I start the game with the "extend monitors" option, the issue comes back.

**Comment by samlee946** [comment] 2020-03-24 08:44
I can reproduce this issue and have been experiencing this for months. I have recently formatted my system drive and installed the latest Windows 10, but the issue is still here. 

This is some info of my OS:
OS Name	Microsoft Windows 10 Education
Version	10.0.18363 Build 18363

This is my monitor setup:
![image](https://user-images.githubusercontent.com/10816366/77404756-9621d180-6d88-11ea-96ae-82e20f6718e9.png)
I am using 1920x1080@240hz for monitor 1, 1080x1920@60hz for monitor 2. For osu!, I'm using fullscreen mode with compatibility mode off. My screen goes black once I click editor.

This is my runtime.log: 
[runtime.log](https://github.com/ppy/osu-stable-issues/files/4374127/runtime.log)

A workaround is to press Ctrl+Alt+Del and then press cancel. My screen goes normal after doing this.

**Comment by ackhack** [comment] 2020-03-31 16:54
This happend to me aswell, i changed to borderless fullscreen and it occured while switching modes, now it doesnt happen in the editor anymore. Maybe the editor menu is always rendered in borderless? Just a guess tho.

**Comment by peppy** [comment] 2020-04-08 01:15
Has anyone tried disabling this "fullscreen optimizations" thing under compatibility options? https://github.com/ppy/osu-stable-issues/issues/412#issuecomment-609473759

**Comment by stanriders** [comment] 2020-04-08 01:18
Doesn't help

**Comment by samlee946** [comment] 2020-04-08 01:19
> Has anyone tried disabling this "fullscreen optimizations" thing under compatibility options? [#412 (comment)](https://github.com/ppy/osu-stable-issues/issues/412#issuecomment-609473759)

I can confirm that didn't work for me.

**Comment by RealistikDash** [comment] 2020-04-08 01:26
Also can confirm that nothing has changed.

On an unrelated note (I am unaware of this information may or may not be useful) when I get the game to start on my second monitor (by dragging the shortcut to my secondary display and starting it) the editor seems to work fine.

**Comment by KaireFeare** [comment] 2020-07-27 11:07
Currently also having this same issue.
Running 2 monitors, main is  2560x1440 144hz Gsync via DP, 2nd is 1920x1080 60hz via HDMI. 
![image](https://user-images.githubusercontent.com/17844825/88535093-364d6880-cfbe-11ea-8e0f-74fca7a906b1.png)
Going into editor with 2 | 1 causes black screen, but when switched from 1 | 2 editor works fine. 
![image](https://user-images.githubusercontent.com/17844825/88535350-980dd280-cfbe-11ea-9d1f-8a204500df86.png)
Editor works in compatibility mode, but adds some latency while playing. 
Running with 1080ti on 451.67 drivers. 
Playing exclusive fullscreen.

**Comment by ricterG** [comment] 2020-09-16 22:29
I have 3 monitors, main is 2560x1440, two side are both 1920x1080, all 144Hz. 

![image](https://user-images.githubusercontent.com/41763965/93398886-009c6180-f842-11ea-83b0-b04aab02567e.png)

I've tested this again with latest driver for my card

![image](https://user-images.githubusercontent.com/41763965/93398313-eada6c80-f840-11ea-9fc3-c928f05999bb.png)

[runtime.log](https://github.com/ppy/osu-stable-issues/files/5235215/runtime.log)

Issue still occurs, whenever I try to switch to borderless window (ie open the editor)

Running in compatibility mode **does** fix it. **Also**, if I go to Windows Display settings and set the resolution for my 1440p monitor down to 1080p, to match my other two monitors, that also fixes the issue.

**Comment by troke12** [comment] 2020-12-04 14:33
is this still no solutions? i have same problem too, running osu in 1600x900 and 1280x1024
tried changing to same resolutions but not fix at all, also running compatibility mode too.

![image](https://user-images.githubusercontent.com/10250068/101175818-9ba61a00-3680-11eb-98d2-bc0e940f392b.png)

**Comment by uwujulio** [comment] 2020-12-20 19:27
I'm having the same issue: opening the editor from a beatmap (while being in singleplayer mode) makes my main monitor go black. Alt+Tab doesn't work, only Ctrl+Alt+Del makes something display on the main monitor. When I click Esc I can see the editor.
In my case setting the same resolution for both monitors OR setting the secondary monitor on the right of the main one solved the issue. (main is 1920x1080 at 144hz and secondary is 1366x768 at 60hz)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/5721374/runtime.log)
![SharedScreenshot](https://user-images.githubusercontent.com/76405883/102722309-9c85af80-4300-11eb-98a5-ee83d54f3121.jpg)
I hope this will be solved, putting physically the secondary monitor on the right of the main one would be a pain for me since I'd have to move the whole setup.

**Comment by peppy** [comment] 2020-12-21 03:21
Thanks for the added info. There's still no solution to this. I still cannot reproduce it locally with similar setups, so there's more to it than simply the arrangement (maybe specific hardware, maybe something else running on your system interacting with the GL context).

I'm not sure when or if this will be fixed, but rest assured we have designed the editor in lazer (a future osu! update) to avoid this issue completely.

**Comment by RealistikDash** [comment] 2021-01-15 13:48
Hey, I'm sorry if this is unnecessary information but I have just changed my GPU to an AMD one (keeping exactly the same software configuration) and the issue is gone, so the issue is not related to non-driver related software.

**Comment by battleof3** [comment] 2021-01-23 03:24
Hi, writing to report I'm experiencing a similar issue. I launch osu!, it appears on one monitor and the other monitor is a black screen. Opening the editor causes the editor to display on the previously black screen.

The window is fixed if I exit fullscreen mode. However, I can only play in borderless window. Windowed mode does not work at all. It stays fixed if I then re-enter fullscreen mode. Another interesting piece of this is that switching between borderless and fullscreen causes the client to restart.

I have also found that creating a shortcut on my desktop, on the monitor I wish osu! to display on, and launching from that shortcut, removes the black screen issue. This is in contrast to launching it from my start menu, which is on one taskbar on the secondary monitor rather than the primary. However, I am still unable to launch osu! in windowed mode and switching between borderless and fullscreen still causes the client to restart. (Now that I think about it, I don't actually know if that's the intended behaviour or not, I was just quite sure it didn't cause a restart around a year ago).

No combination of settings in the Windows compatibility settings affect this behaviour, for me.

Running a new install of Windows 10 20H2, GTX 1070 with driver 461.09. Two identical 1080p 60hz monitors.
[runtime.log](https://github.com/ppy/osu-stable-issues/files/5859579/runtime.log)

![eEmFFLJBMw](https://user-images.githubusercontent.com/25714399/105567480-c7946200-5cf7-11eb-86d7-cf0164596b4b.jpg)
![RPEPEePf5Y](https://user-images.githubusercontent.com/25714399/105567483-c9f6bc00-5cf7-11eb-9b20-7b4e80e4405e.jpg)
![nvcplui_ZEG1RAZZt9](https://user-images.githubusercontent.com/25714399/105567484-cbc07f80-5cf7-11eb-80a6-a82299056628.png)
![ApplicationFrameHost_GnXb40DG3i](https://user-images.githubusercontent.com/25714399/105567485-cd8a4300-5cf7-11eb-8612-8ae646ec6c04.png)

**Comment by syyyr** [comment] 2021-05-03 08:40
Hello, I have some more info on this bug:
1) I have two monitors, my main is 1920x1080 and secondary is 1280x1024
2) If I launch osu on my main monitor and enter editor, I get a black screen. I can solve this by pressing Ctrl+Alt+Del and returning.
3) If I launch osu on my secondary monitor, then I don't get a black screen at all.
4) If I disconnect one of my monitors, everything works fine.
5) This issue is not connected to just osu. I also have problems with video playback, especially when watching videos in Chrome in fullscreen (the video lag and randomly freeze).

**Comment by peppy** [comment] 2021-05-03 08:56
@syyyr thanks for the added information. just to confirm, you can see this same kind of issue happening in chrome *without* osu! running?

**Comment by syyyr** [comment] 2021-05-03 09:56
Yes, the chrome issue is happening even when osu is not running, although it isn't exactly the same issue (no black screen). But I suspect the issues are connected, because they started happening at roughly the same time (possibly after a driver update) and they both have something to do with fullscreen mode. I'm not completely sure though.

I have tried reproducing the chrome issue again and I couldn't do it on Youtube. However, the issue does appear in weird web players (like JWPlayer). Playing two videos in these players in fullscreen makes the videos lag (it looks as if the video can't keep up, then quickly recovers and then falls behind again). Pressing Ctrl+Alt+Del in that situation removes one of the videos from fullscreen (the issue reappears when entering fullscreen again).

https://osu.ppy.sh/community/forums/topics/906325 This guy has a similar problem, he says that DDU and a fresh installation helped him. I have tried his solution just now, and it didn't work for me.

I have tried quitting all other programs and the issue still appeared.

**Comment by syyyr** [comment] 2021-05-03 10:07
More info:
1) Enabling compatibility mode resolves the issue. Compatibility mode AFAIK switches from OpenGL to DirectX. This person seems to have a similar issue and says that his only happens with OpenGL https://www.nvidia.com/en-us/geforce/forums/gaming-pcs/8/300685/two-monitors-different-resolutions-lag-stutte/
2) An easier way of reproducing the issue is to just untick "Fullscreen mode" in the settings menu.

**Comment by troke12** [comment] 2021-05-03 10:59
The easier way for fixing this it's turn off the second monitor and then go to the Editor again.

**Comment by RedCyro** [comment] 2021-06-05 19:43
using Ctrl+Alt+Delete with the black screen fixes the issue for me

**Comment by dothyt** [comment] 2021-10-18 17:31
FYI, I had the exact same issue using two monitors with different resolution and refresh rate for years. Just updated to Nvidia latest game ready driver 496.13. Full screen mode now runs flawlessly. No more compatibility mode or Ctrl+Alt+Delete. Highly suggest people who had this problem give it a shot. For statistics, thumbs up this comment if it works for you, down if it doesn't

**Comment by Richardlx** [comment] 2021-10-18 18:02
Can confirm that 496 does the trick. It also changes how full screen mode behaves, as now opening other windows on top of osu doesn't kick it back to taskbar and shows desktop but keeps osu in the background.

**Comment by troke12** [comment] 2021-10-19 00:38
> FYI, I had the exact same issue using two monitors with different resolution and refresh rate for years. Just updated to Nvidia latest game ready driver 496.13. Full screen mode now runs flawlessly. No more compatibility mode or Ctrl+Alt+Delete. Highly suggest people who had this problem give it a shot. For statistics, thumbs up this comment if it works for you, down if it doesn't

already updated to driver 496 and still not working, i'm using GTX 1050ti

### settings
![screenshot240](https://user-images.githubusercontent.com/10250068/137824863-9d07ff8a-999a-4370-a2af-2c1487cd3d01.jpg)

https://user-images.githubusercontent.com/10250068/137824751-b2a36391-6ed3-44a5-8d99-fdc61c314712.mp4

**Comment by sbourkedev** [comment] 2021-10-25 19:57
Only thing that worked for me was reducing my main monitor's refresh rate to 144Hz, to match my other monitor. Obviously for people whose secondary monitor is only 60Hz, this isn't a good solution. (Both monitors are 1920x1080 btw)

**Comment by kvietcong** [comment] 2021-12-01 01:58
I seem have the same issue. Here are my specs so it can hopefully aid in fixing this.

I have a laptop connected to two monitors. My displays are set up like so:
![image](https://user-images.githubusercontent.com/32186663/144157776-ea04a0e6-b4ad-4396-bbf1-594372246ae2.png)

From left to right:
1. Mini-DP to HDMI (1080p@60hz)
2. HDMI to HDMI (1440p@144hz)
3. Laptop Screen (1080p@60hz)

The issue happens on every single monitor.

I have a GTX 1660ti with the 496.76 Nvidia drivers.

Compatibility Mode fixes this issue but it introduces pretty severe input lag for me. The issue is also solved if I have the admin prompt pop up and escape out of it. Changing resolution or refresh rates sadly did not help.

**Closed** 2022-03-01 01:54 UTC
Labels: will investigate

**Comment by peppy** [comment] 2022-03-01 02:57
Thanks for everyone's patience on this issue. I was hoping nvidia would provide a fix but that hasn't happened until now. I was able to reproduce this over recent months and finally got a chance to look into it (my gaming PC had no dev tools setup so it was a bit of an ordeal).

Should be fixed in the next cutting edge release!

**Comment by ReKessoku** [comment] 2026-02-15 11:40
Too late but i just had this problem again
Nvidia overlay usually messes with a lot of games when its on 
i had to disable the instant replay for it to get solved i hope it helps
