### ISSUE TITLE
Touch Screen incorrectly identified in replay

### ISSUE THREAD

**Issue by Abratexz** [ppy/osu-stable-issues#987] opened 2022-05-20 10:21 UTC
Just passed a loved map just a couple minutes ago, found out it's on Touch Screen mod when I used a Tablet and keyboard to complete it.
https://osu.ppy.sh/scores/osu/4165712501 Replay
https://osu.ppy.sh/beatmapsets/1315615#osu/2726346 Map
![ds](https://user-images.githubusercontent.com/105919305/169508060-7b4d24de-a7f6-4e66-b6aa-e92fcb19083c.png)

**Comment by smoogipoo** [comment] 2022-05-23 06:56
Duplicate of https://github.com/ppy/osu-stable-issues/issues/345

**Closed as completed by smoogipoo** 2022-05-23 06:56 UTC
