### ISSUE TITLE
Black screen while running multiple monitors of different resloutions

### ISSUE THREAD

**Issue by Ohwagg** [ppy/osu-stable-issues#11] opened 2019-09-19 13:07 UTC
Osu! Monitor displays a black screen upon opening the editor or changing resolutions while running two monitors of different resolutions. This black screen disappears allowing you to get back to what you were trying to do when you press Ctrl+Alt+Delete but it's still slightly annoying.

**Comment by peppy** [comment] 2019-09-19 13:11
I'm guessing this only happens in fullscreen?

**Comment by Ohwagg** [comment] 2019-09-19 13:37
Yeah it's a fullscreen only issue from what I can tell

**Comment by peppy** [comment] 2019-09-19 13:40
I'm not sure this will be such a simple fix. Have you considered running in borderless mode instead, as a solution?

**Comment by Ohwagg** [comment] 2019-09-19 14:07
Yeah I have to use borderless for when I

**Comment by Enerugi** [comment] 2019-09-20 04:10
This keeps ocurring to me as well..

Its so annoying because you cant play use the editor in fullscreen mode, only borderless but the main issue is if you change to fullscreen mode in order to play it will also give you black screen.

https://osu.ppy.sh/community/forums/topics/901965?start=7113199

I know there is a temporary solution but I would love to use it in fullscreen ...

**Comment by NiceAesth** [comment] 2019-09-20 09:12
Can reproduce this issue too, it started happening around when I updated my nvidia drivers when they released the gsync for freesync monitors update

**Comment by peppy** [comment] 2019-12-13 03:24
Closing in favour of https://github.com/ppy/osu-stable-issues/issues/207

**Closed by peppy** 2019-12-13 03:24 UTC
Labels: moderate effort required, will investigate
