### ISSUE TITLE
Moving objects in editor by pixels causing great lag

### ISSUE THREAD

**Issue by ItzABC** [ppy/osu-stable-issues#754] opened 2021-05-15 23:39 UTC
When you use the "Ctrl + Arrow" hotkeys to move objects in (std/ctb) editor in the latest version of osu-stable, it randomly causes great lag, and the move would be or not be performed, which is costing unnecessary extra effort when snapping objects by pixels.

**Comment by peppy** [comment] 2021-05-16 03:14
nothing has changed with this code and i can't reproduce. can you include the beatmap you are seeing this on?

**Comment by Nivalyx** [comment] 2021-05-16 16:30
it can happen literally on any beatmap tho. all i need to do to reproduce this bug is to select any object in the editor and press ctrl+any arrow key (i'm using cutting-edge atm and i can confirm this happened to me as well)

also iirc many mappers have been aware of this issue for a while http://twitter.com/DeviousPandaAlt/status/1387491551023140867

**Comment by Nivalyx** [comment] 2021-05-16 16:35
further details :

basically everytime an object in the editor is being moved w/ ctrl + arrow key osu! "freezes" and only responds up a few seconds later after reporting a huge drop in fps (as evident in the bottom-right corner here)

![image](https://user-images.githubusercontent.com/36564236/118404881-0aab8400-b69f-11eb-8b02-3e22391772ce.png)

**Comment by peppy** [comment] 2021-05-17 02:22
Can you link a beatmap where this is happening? I understand what you're reporting, but as my previous reply, cannot reproduce. Nor can I see any reason why this would happen.

My thinking is it may be some external app on your system (windows? discord? something else?) which is handling this keyboard shortcut and doing something weird.

You may be able to help fill in the blanks by turning on performance logging in settings and reproducing the issue. Then attach `performance.log` here for my review.

**Comment by Nivalyx** [comment] 2021-05-17 04:33
ah, okay — this is what i got after i opened osu!, went to the editor immediately, and moved one object at random :

[performance.log](https://github.com/ppy/osu-stable-issues/files/6491106/performance.log)

((i took a quick look at it and apparently the performance.log file is reporting a lot of `Slow Frame Detected at (...) in SelectEdit` and `Slow Frame Detected at (...) in Edit` in it :x))

**Comment by peppy** [comment] 2021-05-17 04:39
So it's freezing on trying to draw a rectangle somewhere on the screen. Which is very weird (something inside winforms, which we basically don't use except for popup windows and the menu bar). Do you have any dialog boxes open in the editor, like the switch-difficulty one?

Also, does this happen when you run windowed?

Are you on the latest windows 10 release?

**Comment by peppy** [comment] 2021-05-17 04:41
Actually hold that thought for one moment, I need to do a bit more digging first.

**Comment by peppy** [comment] 2021-05-17 04:54
@Nivalyx can you also attach your `runtime.log` file from the same kind of scenario?

**Comment by Nivalyx** [comment] 2021-05-17 05:53
ah, okay

[runtime.log](https://github.com/ppy/osu-stable-issues/files/6491364/runtime.log)

also for the record :

- i'm using the latest version of Windows 10
- i'm running fullscreen instead of windowed
- i don't have any dialogue box open in the editor (as far as i'm aware of)

**Comment by Nivalyx** [comment] 2021-05-17 05:56
also for the record :

- i'm using the latest version of Windows 10
- i'm running fullscreen instead of windowed
- i don't have any dialogue box open in the editor (as far as i'm aware of)

**Comment by peppy** [comment] 2021-05-17 06:06
Thanks, this should help track things down. Interestingly, this looks to be a bug which has existed for years or decades.

```
2021-05-17T05:54:21: System.InvalidCastException: Unable to cast object of type 'osu.GameplayElements.HitObjects.HitObject[]' to type 'osu.GameplayElements.HitObjects.HitObject'.
2021-05-17T05:54:21: at osu.GameModes.Edit.Records.HitObjects.Actions.HitObjectMoveGamefieldAction.get_HasChange()
2021-05-17T05:54:21: at osu.GameModes.Edit.Records.ChangeRecord.RemoveUnchangedActions()
2021-05-17T05:54:21: at osu.GameModes.Edit.Records.ChangeManager.ChangeState.RemoveUnchangedRecords()
2021-05-17T05:54:21: at osu.GameModes.Edit.Records.ChangeManager.FinishAction(Boolean forcePop, Boolean undoWhenPopped)
```

**Comment by peppy** [comment] 2021-05-17 06:57
I've fixed this in the latest cutting edge release. Could you please confirm that things feel better?

**Comment by Nivalyx** [comment] 2021-05-17 07:14
tested earlier, things do feel much better now yup 👍

**Comment by smoogipoo** [comment] 2021-05-17 07:18
Closing as resolved.

**Closed by smoogipoo** 2021-05-17 07:18 UTC
