### ISSUE TITLE
Game crashed after placing a note really far before the song starts

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#307] opened 2020-01-05 06:30 UTC
When you scroll behind 00:00:000 you get some wacky stuff... and also it crashes when you place anything before it

**Comment by vekt0r-github** [comment] 2020-01-06 19:59
I think the ability to scroll to a negative time in editor is the unintended behavior; -Sylvari made a post on forums with evidence for this bug in cutting edge 20200102, and it looks like the bug exists in stable 20200104.8 now.
forum post: https://osu.ppy.sh/community/forums/topics/1005343

**Comment by WinterIsPretty** [comment] 2020-01-06 23:06
It's in stable

**Comment by WinterIsPretty** [comment] 2020-01-08 16:48
What if we were able to place notes and add timing outside if the song

**Comment by peppy** [comment] 2020-01-10 10:23
please test latest cutting edge. this issue should be resolved.

**Comment by peppy** [comment] 2020-01-11 14:53
Is now impossible to do. Closing.

**Closed by peppy** 2020-01-11 14:53 UTC
