### ISSUE TITLE
Freezes when typing.

### ISSUE THREAD

**Issue by SWAGEDGAR** [ppy/osu-stable-issues#682] opened 2021-03-15 08:37 UTC
**Describe the crash:** 
It freezes randomly when I type something in search bar. It mostly freezes when I miss click the enter button and click "\" "[" or "]". It also freezes when I try to find the beatmap Honesty idk why.
**Screenshots or videos showing encountered issue:** 
https://youtu.be/Cn8dz0392Oc

**Logs:**
[database.log](https://github.com/ppy/osu/files/6138635/database.log)
[network.log](https://github.com/ppy/osu/files/6138636/network.log)
[performance.log](https://github.com/ppy/osu/files/6138637/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6138638/runtime.log)
**Computer Specifications:** 
![Screen Shot 2021-03-14 at 11 29 27 PM](https://user-images.githubusercontent.com/39568131/111100025-2c608180-851d-11eb-9600-26a595bc447b.png)

**Comment by smoogipoo** [comment] 2021-03-15 08:41
Your video is showing osu!stable but the logs are from osu!lazer. Please open the osu! folder via the button in the game's options, to find the appropriate logs.

**Comment by SWAGEDGAR** [comment] 2021-03-15 18:34
> a

ah sorry! heres the osu!stable logs
[runtime.log](https://github.com/ppy/osu-stable-issues/files/6143684/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/6143685/session.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/6143686/update_success.log)

**Comment by SWAGEDGAR** [comment] 2021-03-15 18:44
> Your video is showing osu!stable but the logs are from osu!lazer. Please open the osu! folder via the button in the game's options, to find the appropriate logs.

ah sorry! heres the osu!stable logs
[runtime.log](https://github.com/ppy/osu-stable-issues/files/6143741/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/6143742/session.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/6143743/update_success.log)

**Comment by smoogipoo** [comment] 2021-03-16 07:58
Unfortunately the logs are empty, probably because you restarted osu!. Please reproduce the issue first and grab the logs without closing osu!.

**Comment by SWAGEDGAR** [comment] 2021-03-16 12:07
> Unfortunately the logs are empty, probably because you restarted osu!. Please reproduce the issue first and grab the logs without closing osu!.

Here are the files 

[runtime.log](https://github.com/ppy/osu-stable-issues/files/6148770/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/6148771/session.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/6148772/update_success.log)
[update.log](https://github.com/ppy/osu-stable-issues/files/6148773/update.log)

**Comment by peppy** [comment] 2021-03-24 08:13
Your logs are still empty. Also I just don't think we can offer support for osu! running under wine in macOS. We're working hard on getting lazer up to standard, so please consider switching to that if this is a crippling issue for you (https://github.com/ppy/osu#releases).

**Closed by peppy** 2021-03-24 08:13 UTC
