### ISSUE TITLE
`Sudden Death` is possible to resurrect in multiplayer

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu-stable-issues#1131] opened 2023-05-19 12:14 UTC
In std mode, not pressing the slider will cause combo break, which will cause sudden death but no miss count.
And when the miss count in score is 0, it can be resurrected.

If there is a miss number in the score, that is, miss>0, the HP will be locked to 0.

It should be the result of not using the flag but using the number of misses

https://github.com/ppy/osu-stable-issues/assets/34775378/0e1e7f9d-9bd4-45af-a565-691952a9d4b9

in the video, I have a slider combo break but result is 100, the HP is can recover.
when I miss a circle and cause miss count, HP lock to 0

**Comment by smoogipoo** [comment] 2023-05-29 06:11
Although this doesn't seem terribly difficult to fix, in the interest of not breaking the game combined with this doesn't sound super common, I think this one's out of scope. Also not sure whether this is working as intended in the first place.

**Closed as completed by smoogipoo** 2023-05-29 06:11 UTC
