### ISSUE TITLE
Reprocessing all beatmaps on import

### ISSUE THREAD

**Issue by Lewskl** [ppy/osu-stable-issues#436] opened 2020-04-24 10:58 UTC
Ever since updating to Stable 20200424.2 today, osu! has started to process all beatmaps whenever I add an osz to the Songs folder with the game open and open song select, with the exception of osu!Direct: Direct causes no problems regardless of which menu I download the map in.

If I download the map any other way, osu! will start processing my maps when I enter song select. The first time it happened, I let it finish, and the map appeared just fine, but it keeps happening consistently. If I interrupt the process, the folder does get created, but the map isn't added to the database. However, if I download the map with the game closed or close the game after downloading the map, the map gets added correctly.

**Comment by peppy** [comment] 2020-04-24 11:05
Does it happen if you use file associations or drag the beatmap into osu!?

Downloading to the songs folder is not really a supported pattern.

**Comment by Dontmakemeeatyou** [comment] 2020-04-24 23:41
Not osz related, but can confirm dragging mp3's into the client to map causes beatmap reprocessing every time.

**Comment by takemybabies** [comment] 2020-04-25 08:35
Can confirm it happens in Stable 20200424.2 when you enter song select screen or press f5 if you are already there, after adding an .osz to the Songs folder/removing any file from the Songs folder (I created an empty folder inside it; beatmap reprocessing only occured when I deleted it). If you wait until all of the beatmaps are reprocessed, they lose their star rating and it has to be calculated again.

**Comment by StormAT** [comment] 2020-04-25 22:53
Yup, I dragged an MP3 into osu (wanted to map for once), and it decided to do a full 80000 beatmap process, and now even if the client calculates difficulties, it gives up on trying to remember what ranks I had on each map. 

I don't know if this makes a difference, but there's a weird error in the bottom right I've never been able to get rid of when I press F5, related to one of my maps. This could be something to do with it? I really have no idea. At least it blocks out the full beatmap process so I can refresh xD

![screenshot794](https://user-images.githubusercontent.com/64335187/80292637-a47c5800-874f-11ea-8d3d-7dd42fce0997.jpg)

**Comment by Dontmakemeeatyou** [comment] 2020-04-25 23:08
> I don't know if this makes a difference, but there's a weird error in the bottom right I've never been able to get rid of when I press F5, related to one of my maps. This could be something to do with it? I really have no idea. At least it blocks out the full beatmap process so I can refresh xD

That's most likely a different issue. Looks like the name might be too long and causing some issues, delete any instances of it in your songs folder and try importing again with a shorter name. 

But you should probably wait till this issue is addressed to import any mp3's but, future reference.

**Comment by Lewskl** [comment] 2020-04-25 23:09
> Does it happen if you use file associations or drag the beatmap into osu!?

Just tested, happens with both of these methods as well

**Comment by takemybabies** [comment] 2020-04-26 08:24
> 
> 
> > Does it happen if you use file associations or drag the beatmap into osu!?
> 
> Just tested, happens with both of these methods as well

This might help, I tested this today but with different results. 

**Having osu! open and downloading .osz files from the browser to any folder other than Songs, then either dragging the file in osu! or using file associations (double-clicking) caused _no issues_.**

When using any of these methods on **.mp3** files or **downloading .osz directly to the Songs folder** (unless osu! is closed): all of the beatmaps will process right in front of your eyes, thus producing **this issue**.

**Comment by Lewskl** [comment] 2020-04-26 12:07
> **Having osu! open and downloading .osz files from the browser to any folder other than Songs, then either dragging the file in osu! or using file associations (double-clicking) caused _no issues_.**
> 
> When using any of these methods on **.mp3** files or **downloading .osz directly to the Songs folder** (unless osu! is closed): all of the beatmaps will process right in front of your eyes, thus producing **this issue**.

seems to work for me too, wonder why osu! behaves differently when the file's in Songs

closing since file associations are convenient enough and peppy doesn't want to support downloading to Songs, although to me it seems really weird that it isn't supported since osu! does say "New beatmap detected" etc when you download one to Songs with osu! open

**Comment by peppy** [comment] 2020-04-26 12:10
I plan on investigating this, so please leave it open.

**Comment by peppy** [comment] 2020-04-26 15:57
I can't seem to reproduce by copying osz files to the songs folder. Can you explain the exact process you're using? Are you saving directly from the browser to the songs folder to reproduce this?

**Comment by xuanhaivptthn** [comment] 2020-04-26 16:33
In my case, download .osz file directly to the songs folder and then press f5 ingame or open .osz will reprocess the whole folder

**Comment by Synaelle** [comment] 2020-04-26 18:43
Here is a video of the problem, it's doing that with every osz/mp3 https://youtu.be/y-h5VQzYyQ4

**Comment by peppy** [comment] 2020-04-26 23:19
Your video shows you saving from the browser to the songs folder. Can you try saving somewhere else then dragging in?

For what it's worth, I can reproduce the issue with .mp3s.

**Comment by peppy** [comment] 2020-04-27 00:41
Could you all please test as many scenarios as you can on cutting edge? I've pushed a fix which works locally but it's very hard to test different configurations and usage patterns.

**Comment by Dontmakemeeatyou** [comment] 2020-04-27 00:48
Since I only had the issue with mp3 files, I could only test those. Seems to be fixed on CE. Tried from all different menu's and never had it prompt a reprocess.

**Comment by peppy** [comment] 2020-04-27 12:30
Fix has been confirmed by many people. Pushed out to stable.

**Closed by peppy** 2020-04-27 12:30 UTC
