### ISSUE TITLE
Switching audio devices while editing map causes incorrect audio frequency

### ISSUE THREAD

**Issue by TheBicPen** [ppy/osu-stable-issues#409] opened 2020-03-29 01:36 UTC
I've encountered this issue on Windows 10. Switching audio devices while editing a map with the playback speed set to a value below 100% causes the frequency to shift by that percentage as well.

Steps to reproduce: 
- open map in editor
- set playback speed to 25/50/75%
- pause playback
- switch audio devices (can be done by unplugging headset)
- resume playback
The audio will now play at 25/50/75% frequency. I assume this is unintentional because switching playback speed normally does not cause the frequency to shift

**Comment by peppy** [comment] 2020-03-29 02:54
Thanks for reporting this issue! We will not be addressing this in stable for the time being due to limited time and focus on lazer for the following reasons:

- It is an issue not many users are likely to have
- Fixing it is non-trivial and will take over 2 hours (our general cutoff for stable issues that don't affect more than 1% of the community).
- It is already fixed on [osu!lazer](https://github.com/ppy/osu) (confirmed).

**Closed by peppy** 2020-03-29 02:54 UTC
