### ISSUE TITLE
crash during play

### ISSUE THREAD

**Issue by Fish-Warden** [ppy/osu-stable-issues#309] opened 2020-01-05 16:44 UTC
Game crashes at random points during gameplay. GPU usage spikes to 100% before the crash. I have frame limit at 144. Crash happens on cutting edge and stable.

[session.log](https://github.com/ppy/osu-stable-issues/files/4023661/session.log)
[performance.log](https://github.com/ppy/osu-stable-issues/files/4023662/performance.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/4023663/runtime.log)

I can include event viewer information as well if necessary.

**Comment by Ceotom** [comment] 2020-01-05 17:08
Are you sure that attached the correct logs? You say that you set frame limit at 144, but if look at the logs this is not true.
If you see "osu! crashed" after crash you can click on this and copy stacktrace.
Also error log from windows event viewer will not be excess.

**Comment by Fish-Warden** [comment] 2020-01-05 18:13
I had the frame limiter set on the optimal setting and went into osu!.<username>.cfg and set the custom frame limit to 144. The game doesn't give the osu! crashed after the crash, so I can't copy the stacktrace unfortunately. I've included event viewer information in a screenshot.

![image](https://user-images.githubusercontent.com/59536566/71784060-f6407d00-2fbc-11ea-896c-5178a7be7078.png)

![image](https://user-images.githubusercontent.com/59536566/71784078-2ee05680-2fbd-11ea-90b7-596fffa43491.png)

**Comment by Ceotom** [comment] 2020-01-05 18:33
> set the custom frame limit to 144

It will not matter until FrameSync is equal to Custom.

Also try to run game in compatibility mode. (Should not help, but this information may be useful)

**Comment by Fish-Warden** [comment] 2020-01-06 02:25
I tried setting FrameSync to custom and custom frame limit to 288, which still crashed. I also set it to compatibility mode, where it still crashed. 

[session.log](https://github.com/ppy/osu-stable-issues/files/4024463/session.log)
[network.log](https://github.com/ppy/osu-stable-issues/files/4024464/network.log)
[performance.log](https://github.com/ppy/osu-stable-issues/files/4024465/performance.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/4024466/runtime.log)

**Comment by smoogipoo** [comment] 2020-01-06 03:47
This is likely going to be an issue with your graphics drivers. Please give us a dxdiag log (follow the instructions on https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe), and check for any updates to your drivers.

**Comment by Fish-Warden** [comment] 2020-01-06 04:46
Here's the dxidag log: 
[DxDiag.txt](https://github.com/ppy/osu-stable-issues/files/4024744/DxDiag.txt)

My graphics drivers and sound drivers are updated

**Comment by peppy** [comment] 2020-01-08 06:16
This is almost definitely related to your skin. Also a duplicate of https://github.com/ppy/osu-stable-issues/issues/302. Could you please post your skin to that issue?

**Closed by peppy** 2020-01-08 06:16 UTC
