### ISSUE TITLE
Crashes during song with specific skin

### ISSUE THREAD

**Issue by LeonardoCrocchini** [ppy/osu-stable-issues#302] opened 2020-01-04 13:24 UTC
There is no "Osu! crashed" window or anything it just goes away doing a strange sound (interference like).
Things I know:

- is not beatmap related.
- it started happening after installing a skin.
- seems to be related to bass.dll (maybe there is a bug in there?)
- it usually happens at the end of maps, but also happened just before a pause.

platform: Windows

From the application log on windows i recovered this:
Faulting application name: osu!.exe, version: 1.3.3.7, time stamp: 0x5e0f8cfc
Faulting module name: bass.dll, version: 2.4.15.0, time stamp: 0x5df8e321
Exception code: 0xc0000005

I would post the log file but i can't seem to make it crash anymore.
Even if it doesn't crash anymore there is still the interference-like sound during maps so the problem didn't solve itself.

**Comment by LeonardoCrocchini** [comment] 2020-01-06 23:24
I experienced another crash and this time i have the log file
[runtime.log](https://github.com/ppy/osu-stable-issues/files/4028174/runtime.log)
The map i was playing was [Ima Koko] https://osu.ppy.sh/beatmapsets/687493/download
the crash happened right at the end on the final note

**Comment by peppy** [comment] 2020-01-07 02:26
The skin probably has corrupt files. Please attach the skin.

**Comment by LeonardoCrocchini** [comment] 2020-01-07 13:52
usually the skin I use is this https://drive.google.com/open?id=1C46U-QV9OwgFgxtJAk5IqL5zGCJLQGrL
PS: sorry for the long time to answer but when I got your message it was 3/4 am for me

**Comment by Fish-Warden** [comment] 2020-01-09 04:05
This is the skin I use that has presumably the same issue. http://www.mediafire.com/file/npp0ay4aul04asu/Girls%20Frontline.osk

**Comment by LeonardoCrocchini** [comment] 2020-01-09 08:41
After experiencing the problem I changed the skin (I'm using Beastroll's one) and the problem went away the only thing I can suggest you is to change your skin @Fish-Warden

**Comment by peppy** [comment] 2020-01-10 10:23
please test latest cutting edge. this issue should be resolved.

**Comment by Ceotom** [comment] 2020-01-10 12:59
Fixed for me

**Comment by peppy** [comment] 2020-01-10 13:08
closing for now. please comment if anyone can still reproduce.

**Closed** 2020-01-10 13:07 UTC

**Comment by etisHere** [comment] 2021-12-26 03:39
Old but I'm having this issue, Pretty sure its something to do with the sound files because each skin i have issues with i can swap the sound files with a skin that works and it seems to fix the issue. (This is on Stable)
