### ISSUE TITLE
Osu! Lag spikes when discord is running

### ISSUE THREAD

**Issue by Deynoy** [ppy/osu-stable-issues#1152] opened 2023-08-23 14:33 UTC
I've been having this problem for a long time and searching for an answer didnt help. I tried using compatibility Mode, disabling hardware acceleration in discord, changing osu settings, disabling every unnecessary program etc. and it gave no results. When i have discord running in the background (even without the in-game display function or whatever it is called) I constantly get lag spikes, that make a frozen frame for 0.5s and after it I can see that my input latency jumped from 2ms (thats what i usually have) to 10ms+, also there is another problem, thats kinda similar. When i alt tab from osu and do something different, (like google something) when i comeback to the game, in the first +/- 100 combo of map i get a black screen for 1s where i cant aim or click. This second problem occurs  even without discord opened. Maybe the answer is the same for both problems.

**Comment by peppy** [comment] 2023-08-23 15:22
probably amd driver issues

**Comment by Deynoy** [comment] 2023-08-23 18:33
okay, so updated my amd rx 480 drivers to the newest, stable ones and the problem got even worse. When i have discord opened it still has the same problem, but now when i start or end a map, I get a black screen for 0.5s where i can't move my cursor. It happens right after i start a map (by clicking enter or the logo in bottom right). Tried to record it with OBS screen capture, but the moment i get into song selection in osu it gets black. It comes back to normal when I start playing a map.
**edit:**
I recorded it with OBS game capture (before the drivers update it didnt work with game capture, only screen one worked), but it doesnt show the same thing as my monitor does (I see the thing i wrote above). Instead it shows a huge latency spike in bottom right that happens in the same moment.

https://github.com/ppy/osu-stable-issues/assets/81430786/607a2a58-4d9a-49ec-8c79-e599ac9fd57a

Here are images of Frame Time Graph, red ones happen when i use any function in osu, like F1, F3, CTRL+O, ESC and green ones (and purple afterwards) are when i select a map. When I start a map or end it, it goes red and green.
![image](https://github.com/ppy/osu-stable-issues/assets/81430786/fe30bf6c-6e6a-401c-a840-81ba9a891cbc)
![image](https://github.com/ppy/osu-stable-issues/assets/81430786/935577df-3e55-40fb-b801-ffc39fe14038)

**Comment by smoogipoo** [comment] 2023-08-24 01:16
- We can't address the Discord issue. Report it to Discord instead.
- The second issue is a duplicate of https://github.com/ppy/osu-stable-issues/issues/1092 .

(Actually both of these issues could be related to https://github.com/ppy/osu-stable-issues/issues/1092).

**Closed as completed by smoogipoo** 2023-08-24 01:16 UTC
