### ISSUE TITLE
osu! shows outdated star rating after making edits to a pending beatmap

### ISSUE THREAD

**Issue by Dopaminos** [ppy/osu-stable-issues#870] opened 2021-10-30 11:29 UTC
Bug: If you will make your map out of submitted .osz ver, star rate will be counted out of submitted map, not your one.
Solve: Use site star rate correction only for submitted maps. Updated and Not Submitted maps shouldn't be corrected.
[Video of bug](https://cdn.discordapp.com/attachments/312266210215723009/903966699781505024/2021-10-30_14-18-40.mp4)

**Comment by Dopaminos** [comment] 2021-10-30 11:30
It works and with renamed diffs what became Not Submitted after rename

**Comment by apollo-dw** [comment] 2021-10-30 14:04
duplicate of https://github.com/ppy/osu-stable-issues/issues/864

**Comment by Dopaminos** [comment] 2021-10-30 16:00
it SHOULDN'T work like this. kinda dumb

**Comment by peppy** [comment] 2021-10-31 14:28
Can you explain what scenario you are changing a ranked beatmap and overwriting the existing difficulty rather than making a new one?

**Comment by Dopaminos** [comment] 2021-10-31 14:55
making edit of beatmap when modding. f/e you are trying to show to mapper what some sections of his map is overdone and you just want to edit it, ctrl+s, screenshot star rate and get your map back just to show, what one jump is making half of map
(when ranked - no. when pending (need mods) - yes)

**Comment by peppy** [comment] 2021-10-31 15:03
I see, that makes a bit of sense. Context is always important for issues like this.

We can probably show the "local" star rating on hover of the text, or next to the online one. Will have a think about it.

**Closed as completed** 2021-11-02 09:33 UTC
