### ISSUE TITLE
Client doesn't display animated catcher when in "User" skin folder

### ISSUE THREAD

**Issue by Snowleopard-osu** [ppy/osu-stable-issues#813] opened 2021-08-14 03:57 UTC
**Client version**: b20210810cuttingedge
**OS**: Windows 10 Pro 21H1 (19043.1110)
**When did this start**: Some time in the last 1-3 weeks
**Skin being used**: [skin.owo.lt](https://skin.owo.lt)

**Video of issue**: [https://streamable.com/4dp168](https://streamable.com/4dp168)

Some time in the last couple of weeks my animated catcher has stopped working when being used via a skin folder called `User`. The contents of this folder are a direct copy and paste of every file in my `wwwUp2Date` folder also demo'd in the above video. All other skin elements are still working as far as I can tell, only the animated catcher is not working and the default Yuzu catcher gets displayed instead.

This is a somewhat minor issue but I use the `User` skin folder due to it being selected automatically by the client when launching in tournament mode.  I don't think the animated catcher has ever worked when launched in tournament mode, but it is really odd that it stopped working in normal mode recently (and only when the `User` folder is being used).  Has anything changed about skinning support in the last few weeks, specifically relating to the `User` folder?  I do completely clear out the folder before copying skins into it, so it is a complete 1:1 match with my `wwwUp2Date` folder.

Here is the catcher file formatting:
![](https://images-ext-2.discordapp.net/external/1cQnfPhnX9ZGRdw6fW7LlWot5nelmFaphJzxMd7QEOU/http/s.owo.lt/ggqnA8v0)

Attaching runtime log, but everything looks pretty normal in it.

[runtime.log](https://github.com/ppy/osu-stable-issues/files/6985853/runtime.log)

**Comment by peppy** [comment] 2021-08-14 04:13
User is a special folder which takes on different behaviour from other skins. It is only intended for small changes, and doesn’t support skin versioning (which is likely the reason it doesn’t work).

That said, nothing has changed surrounding any related logic. You must have made an unintended change somewhere.

May want to ask on the help forum if you want more specifics about skinning, but this is not a regression.

**Comment by Snowleopard-osu** [comment] 2021-08-14 04:23
Hmm I'm fairly certain it was working from the User folder a few weeks ago (again only in normal mode, not tournament mode).  I could be mistaken though.

**Comment by peppy** [comment] 2021-08-14 04:42
Nothing has changed, so as I said, it may be an inadvertent change to other surrounding resources, or something in skin.ini.

**Comment by WinterIsPretty** [comment] 2021-08-16 15:17
ryuuta was disabled in the skin version 2.3 and the versions after that use catcher

**Comment by h3oCharles** [comment] 2021-08-21 00:18
user uses `latest` in Version in skin.ini, therefore fruit-ryutta is unused, try using that animation on fruit-catcher-idle

**Comment by peppy** [comment] 2021-08-24 06:17
@h3oCharles thanks for investigating. Closing this one as user misunderstanding.

**Closed by peppy** 2021-08-24 06:17 UTC
