### ISSUE TITLE
Beatmap Registering as "Unknown"

### ISSUE THREAD

**Issue by dudemanPN** [ppy/osu-stable-issues#747] opened 2021-05-04 01:51 UTC
Peppy has also asked me to post this here. Beatmaps are being categorized as "unknown" after downloading and refreshing several times. There were two fixes that I have come across: 1) When downloading new maps, I have to switch the rankings to Global instead of Local and refresh every single difficulty to categorize it into Ranked from Unknown; 2) Deleting the local database and refreshing when I get into game.

This started happening about a week ago and I do not know why.

Is there another fix so I would not have to refresh every single difficulty to make sure the song is categorized as Ranked?

Video:
https://youtu.be/3oH7kpPkO1M

**Comment by venix12** [comment] 2021-05-05 21:23
a duplicate of #742 perhaps?

**Comment by peppy** [comment] 2021-05-06 07:45
Could you please share which version of osu! you are running?

Also, can you try the same thing but:
- Try going back to the main menu (don't use F5, and wait 30s at the main menu before checking again)
- Try quitting and then restarting the game (wait 30s before going into song select for the first time)

**Comment by dudemanPN** [comment] 2021-05-06 09:08
> Could you please share which version of osu! you are running?

osu! Stable 20210423.2

> Also, can you try the same thing but:
* Try going back to the main menu (don't use F5, and wait 30s at the main menu before checking again)
This one seems worked! Thank you. 

* Try quitting and then restarting the game (wait 30s before going into song select for the first time)

> a duplicate of #742 perhaps?

Yes.

**Comment by dudemanPN** [comment] 2021-05-09 14:40
Unfortunately, I am back with the same problem of beatmaps not properly categorizing themselves. I don't know what happened and why it just stopped working after being fixed.

I tried reinstalling the client and the other solutions previously mentioned but they also didn't work. This time, hitting F5 will not always categorize them properly. Sometimes it takes two or three refreshes to categorize it.

Thank you in advance.

**Comment by Gabril07** [comment] 2021-05-15 16:22
So.. I have the same problem, but it happened with my olds ones, and I lost all my olds runs, except my highscores going in global scores...

**Comment by Sleepteiner** [comment] 2021-05-17 18:11
Same issue. Just as it says in #742, this happens with newly downloaded maps and on the other difficulties of a mapset if you look at one of the difficulties of that mapset in the editor. The only way to practice or study a ranked map is to use the editor, so it isn't uncommon for experienced players to use the editor on ranked maps a lot.

Also just as #742 says, this used to be an issue a while ago, but then it was fixed, or at least stopped happening. It started happening again for me as well right around when #742 was posted. I have no idea why. Most people I've asked are experiencing the same things.

**Comment by peppy** [comment] 2021-05-18 19:14
I found a potential cause of this and have pushed a fix to cutting edge. Please give it a try and see if it helps.

**Comment by dudemanPN** [comment] 2021-05-19 09:03
This update with cutting edge worked! Thank you much!

**Closed** 2021-05-19 09:07 UTC
