### ISSUE TITLE
Can not start new beatmaps while not having an account logged-in

### ISSUE THREAD

**Issue by SHA-256-hash** [ppy/osu-stable-issues#738] opened 2021-04-22 20:39 UTC
After recent changes, if creator field is empty you can't press OK to start a new map.
You should use Guest in creator field if player is not logged in the game.

**Comment by Joehuu** [comment] 2021-04-22 21:45
Duplicate of https://github.com/ppy/osu-stable-issues/issues/689. You can use cutting edge for now.

**Comment by peppy** [comment] 2021-04-23 00:47
Should be going live today or tomorrow as well.

**Closed by peppy** 2021-04-23 00:47 UTC
