### ISSUE TITLE
SpinnerFrequencyModulate with short audio file causes audio to misbehave

### ISSUE THREAD

**Issue by minelolpride** [ppy/osu-stable-issues#311] opened 2020-01-06 00:45 UTC
When playing with any skin that contains a very short yet valid audio file for "spinnerspin", and when SpinnerFrequencyModulate is set to 1, the game seems to not loop back to the beginning of the audio file. Instead, it will continue playing whatever data it can find after it, which can include other skin assets or something that causes the game to crash pretty hard. I believe this comes in part from the recent audio update, as enabling "Audio Compatibility Mode" will prevent this from happening as well.

I have recorded a video of this happening as well [here](https://youtu.be/NoOMQ0YNm44). In the video I was using the stable branch, b20200104.8, and after updating to Cutting Edge (which gave me b20200104.6cuttingedge) the problem persisted.

Workarounds to this I have found include doing any one of the following: Replacing the "spinnerspin" file with either something longer or even a completely invalid/empty file, disabling SpinnerFrequencyModulate in "skin.ini", or enabling "Audio Compatibility Mode".

I have attached all log files from osu!/Logs as well as a 'spinnerspin.mp3' that has been created and can consistently reproduce the effect. I have also attached logs pulled from Event Viewer as well if they are of any use.

This may be just an edge-case scenario at work here, so if this happens to not be fixable then I understand.

[network.log](https://github.com/ppy/osu-stable-issues/files/4024293/network.log)
[performance.log](https://github.com/ppy/osu-stable-issues/files/4024294/performance.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/4024295/runtime.log)
[session.log](https://github.com/ppy/osu-stable-issues/files/4024296/session.log)
[update.log](https://github.com/ppy/osu-stable-issues/files/4024297/update.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/4024298/update_success.log)

[spinnerspin.zip](https://github.com/ppy/osu-stable-issues/files/4024299/spinnerspin.zip)
[event_viewer_logs.txt](https://github.com/ppy/osu-stable-issues/files/4024304/event_viewer_logs.txt)

**Comment by Ceotom** [comment] 2020-01-06 09:29
I can reproduce this, but only with your spinnerspin.mp3.

**Comment by peppy** [comment] 2020-01-08 06:31
Likely related / duplicate of https://github.com/ppy/osu-stable-issues/issues/302.

**Comment by Ceotom** [comment] 2020-01-08 15:41
Yes, this same issue

**Comment by peppy** [comment] 2020-01-09 02:49
Will close this in favour of that other issue.

**Closed by peppy** 2020-01-09 02:49 UTC
