### ISSUE TITLE
Editor timeline bugs

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-stable-issues#320] opened 2020-01-08 23:28 UTC
Listening to the whole song then pressing jump to end key makes it so you can't scroll in the duration of the song also if you use the scroll wheel up.
When you press the jump to end button on your keyboard it doesn't go to 100% unless you listen to the rest of the song. It only happens when you are at 100% and you press that key.

Also the play from beginning key, the audio pause key, and the space bar make it so you go past 100% except the play from beginning key make it so you can go past 100% except the song plays even if you stop it unless you click on the timeline.

also if you press the play from beginning key when at the negative timeline it plays the song where your at and doesn't jump to the beginning of the song.

**Comment by peppy** [comment] 2020-01-09 02:55
Closing as duplicate of https://github.com/ppy/osu-stable-issues/issues/301. Please search first.

**Closed by peppy** 2020-01-09 02:55 UTC
