### ISSUE TITLE
Spamming short spinners repeatedly makes the player unable to quit out of the map

### ISSUE THREAD

**Issue by Shaper021** [ppy/osu-stable-issues#1101] opened 2023-03-10 20:23 UTC
Before reading, same issue mentioned in #1069 #1074 #1078 

Basically, players can be softlocked in a map with a lot of really short (ninja) spinners in a row which prevents them from just leaving the map by hitting escape, so they're forced to ALT+F4 or kill osu using the task manager. This is caused by the [stable/cutting edge hotfix update](https://osu.ppy.sh/home/changelog/stable40/20221208.5) which was originally only aimed at a dozen players to begin with but impacts players that aren't involved in anything spinning related and in the longer run it does more harm. These maps can be made really easily and by anyone, so naturally there are a lot of "bait maps" where a really racist/offensive song is used and it traps the player in it until they forcefully quit out of the game, which can damage their twitch/youtube stream or overall enjoyment of the game. A friend of mine made a map that spams really short spinners repeatedly to demonstrate the issue in hand, see clips below: 

https://clips.twitch.tv/EnthusiasticEagerTofuDeIlluminati-fCTx4t2RvDwGCdON
https://clips.twitch.tv/TolerantResoluteRadishTBTacoLeft-kP_APlV3NfYgVZXY
https://clips.twitch.tv/ObservantShakingBananaRedCoat-wWMMROhBAyV-fKZR
https://clips.twitch.tv/BelovedEasyBurritoYee-IPpDyMTM-qzmNtaN
https://clips.twitch.tv/BusyMildParrotVoteYea-5XVwl4uju7iExtd0

**Comment by peppy** [comment] 2023-03-13 06:00
Duplicate of #1069, we will track there.

**Closed as not planned by peppy** 2023-03-13 06:00 UTC
