### ISSUE TITLE
Black screen when leaving Full screen Mode

### ISSUE THREAD

**Issue by SampleCoin** [ppy/osu-stable-issues#654] opened 2021-01-27 00:44 UTC
Hi, i have an dual Monitor setup where one Monitor is vertical. Every time i try to get out of full screen (like going into the Editor) osu goes completely black, but this affects only the Image and not the sound.

Here's an example: https://imgur.com/u6eZudZ

The cause of this is the vertical Monitor. When i put him in landscape again, the Problem is not there anymore. Ive already completely removed the Nvidia driver and installed the latest.

Other people seem to have the same issue too: https://osu.ppy.sh/community/forums/topics/906325

**Comment by smoogipoo** [comment] 2021-01-27 04:04
Seems like this is probably a duplicate of https://github.com/ppy/osu-stable-issues/issues/207

**Closed by smoogipoo** 2021-01-27 04:04 UTC
