### ISSUE TITLE
pause-loop never plays

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu-stable-issues#19] opened 2019-09-19 17:38 UTC
When you pause active gameplay, pause-loop.mp3 (or any other valid audio format) is supposed to play, but it doesn't.

https://twitter.com/LittleEndu/status/1101903701718036480

**Comment by aerouk** [comment] 2019-09-19 18:20
I feel like this might have been hotfixed a month or two ago since it was stuck playing even after unpausing

**Comment by peppy** [comment] 2019-09-19 18:22
Is this specific to skins? Fine on default?

**Comment by LittleEndu** [comment] 2019-09-19 18:25
It's not specific to skins, it doesn't play anything even on default skin.

If it was fixed at some point between March and now, it sure has broken again. Or it just isn't as simple of a fix...

**Comment by peppy** [comment] 2019-09-19 18:41
Very weird, it's working as intended here. I wonder if it's interacting with a specific setting you have on?

**Comment by LittleEndu** [comment] 2019-09-19 19:00
OK, it does work as intended on a fresh install. I'm not sure though what setting would prevent only pause-loop from playing.

**Comment by LittleEndu** [comment] 2019-09-19 19:02
But it doesn't work on cuttingedge. Just switched the fresh install to cuttingedge and now pause-loop doesn't play.

**Comment by peppy** [comment] 2019-09-19 19:47
Can confirm, broken on CE but not Beta or Stable.

**Comment by peppy** [comment] 2019-09-19 20:15
Fixed in next cutting edge release!

**Closed by peppy** 2019-09-19 20:15 UTC
Labels: easy fix, will investigate
