### ISSUE TITLE
song selection screen lags if search returns few/no results

### ISSUE THREAD

**Issue by InvisibleSymbol** [ppy/osu-stable-issues#93] opened 2019-09-22 20:00 UTC
song selection screen lags in relation to the amount of results you get. The less results you get, the higher the lag is.
# steps to reproduce:
- search for something you don't have
# screenshots/video:
https://streamable.com/eqsfq
# logs:
```
2019-09-22T19:44:35: ---------- Slow Frame Detected at 6.00s in SelectPlay ----------
2019-09-22T19:44:35: Statuses: [Active] [Bancho] [Severe]
2019-09-22T19:44:35: 
2019-09-22T19:44:35: Game       6,196
2019-09-22T19:44:35: Mode       2,183
2019-09-22T19:44:35: Audio     66,026
2019-09-22T19:44:35: 
2019-09-22T19:44:35: BetweenFrames     0.00
2019-09-22T19:44:35: Update          253.22
2019-09-22T19:44:35: Scheduler         0.00
2019-09-22T19:44:35: Draw              0.95
2019-09-22T19:44:35: Sleep             0.03
2019-09-22T19:44:35: SwapBuffer        0.31
2019-09-22T19:44:35: 
2019-09-22T19:44:35: This Frame 254.56
2019-09-22T19:44:35: Avg. Frame  11.75
2019-09-22T19:44:35: Curr FPS       64
2019-09-22T19:44:35: 
2019-09-22T19:44:35: NativeText           1
2019-09-22T19:44:35: TextureGen           1
2019-09-22T19:44:35: TextureUpload        1
2019-09-22T19:44:35: 
2019-09-22T19:44:35: Call stack follows:
2019-09-22T19:44:35: 
2019-09-22T19:44:35: - Boolean IsAscii() @ 0
2019-09-22T19:44:35: - Int32 IndexOf(System.String, System.String, Int32, Int32, System.Globalization.CompareOptions) @ 175
2019-09-22T19:44:35: - Int32 IndexOf(System.String, Int32, Int32, System.StringComparison) @ 480
2019-09-22T19:44:35: - Boolean #=zu05Tl01_31av(#=zjaTdTILP18xFcw41XR7lCA9WrwcjNwGPvf8sqIL1o_F$, System.String) @ 285
2019-09-22T19:44:35: - Boolean #=zaDuWcL3QLr7KWgIcjg==(#=zjaTdTILP18xFcw41XR7lCA9WrwcjNwGPvf8sqIL1o_F$) @ 13
2019-09-22T19:44:35: - Void #=z6DUkJMM=(Boolean) @ 789
2019-09-22T19:44:35: - Void #=zoRasjDA=() @ 444
2019-09-22T19:44:35: - Void #=zmebAkme93YTFy5pZDg==(#=zdXJHJXjBwMw1NP1dWsY3DQs=) @ 13
2019-09-22T19:44:35: - Void ForEach(System.Action`1[T]) @ 89
2019-09-22T19:44:35: - Void #=z0ug$dpuNM9E10GwIrw==() @ 97
2019-09-22T19:44:35: - Void #=zMdabMU0=(#=zls8w7QN3Wi2O9xHLDeFCfa4=) @ 2982
2019-09-22T19:44:35: - Void #=zoRasjDA=() @ 462
2019-09-22T19:44:35: - Void #=zJVmxUNj3G8EK(System.Object, System.EventArgs) @ 27
2019-09-22T19:44:35: - Void #=zNdpFChc=(System.Object, System.EventArgs) @ 26
2019-09-22T19:44:35: - Void #=zQIo4bkRAZ5cdIcd9YQ==(System.Object, System.EventArgs) @ 105
2019-09-22T19:44:35: - Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32) @ 34
2019-09-22T19:44:35: - Boolean System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32) @ 1070
2019-09-22T19:44:35: - Void RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext) @ 610
2019-09-22T19:44:35: - Void RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext) @ 60
2019-09-22T19:44:35: - Void Run(System.Windows.Forms.Form) @ 50
2019-09-22T19:44:35: - Void #=zg0PfqWM=() @ 115
2019-09-22T19:44:35: - Void #=zg0PfqWM=() @ 36
2019-09-22T19:44:35: - Void #=zqHN6XQ_kPvBh(System.String, Boolean, Boolean) @ 471
2019-09-22T19:44:35: - Void #=zOUpWDA8=(System.String[]) @ 1589
2019-09-22T19:44:35: - Void #=zZmiFDiY=() @ 1951
2019-09-22T19:44:35: - Void #=zSq37p3I=() @ 6
```
# version/setup:
- latest ce (`b20190922cuttingedge`)
- windows 10 1903/18362.356 (64 bit)

**Comment by peppy** [comment] 2019-09-23 02:31
it's probably less the number of results and more the length of the search query?

**Comment by peppy** [comment] 2019-09-23 02:34
250ms lag on a search is within acceptable bounds. this should be fixed on lazer already; let's leave it at that.

**Closed by peppy** 2019-09-23 02:34 UTC

**Comment by InvisibleSymbol** [comment] 2019-09-23 14:49
> it's probably less the number of results and more the length of the search query?

No, it's the amount of result that matter. Stuff like ["status="](https://i.fiery.me/OTff.jpg) (guaranteed to return nothing) lags more than  ["road of resistance bpm>=0 stars>=0"](https://i.fiery.me/n68W.jpg).

> 250ms lag on a search is within acceptable bounds.

250ms is okay??? This is 250ms on an overkill (for osu! at least) system. Sadly, I can't try it on a lower perf system, but I imagine it to be much worse.

---
Overall, I'm okay with this not being fixed (since it seems like you aren't interested in doing it, and it's pretty much an edge case), but 
>  this should be fixed on lazer already; let's leave it at that.

is just simple ignorance... ofc it's fixed on lazer, _the problem was never there to begin with!_

**Comment by peppy** [comment] 2019-09-24 01:58
We are still focusing our time on making lazer the best it is. This repository is strictly for 5 minute fixes, which I guarantee this is not. Performance optimisations are out of scope.

The issue is not present in lazer because this was one of the hundreds (or thousands) of considerations we had when creating it, to fix existing issues like this. Hope this is understandable.
