### ISSUE TITLE
importing skins by drag & drop causes interesting looking graphical issues

### ISSUE THREAD

**Issue by xxfoofyxx** [ppy/osu-stable-issues#202] opened 2019-11-02 04:42 UTC
on a fresh install of osu! i decided to import a skin using drag & drop, initially the game froze for a bit, then when it unfroze the osu!direct panel text turned to the word "no" stretched out (sounds ridiculous i know) and the FPS counter was displaying blocks instead of numbers.
![osu glitch](https://user-images.githubusercontent.com/37008464/68066149-7cb0b800-fd09-11e9-8f68-d8fbf6b7f42d.png)
ignore the discord overlay in that screenshot, in-game screenshotting wasn't working and i was screensharing to a friend so he took it for me.

**Comment by smoogipoo** [comment] 2019-11-05 02:13
These issues are likely caused by discord itself. Please try to close discord and OBS (if you have it open), and see if the issue reproduces.

**Comment by peppy** [comment] 2019-12-06 01:14
Closed as this has been reproduced a few times and caused by the discord overlay.

**Closed by peppy** 2019-12-06 01:14 UTC
Labels: will investigate
