### ISSUE TITLE
Unable to update beatmap on site.

### ISSUE THREAD

**Issue by Akareh** [ppy/osu-stable-issues#706] opened 2021-03-29 20:47 UTC
Hello!
I'm part of a collab set in osu which can't be updated, the set can be accesed here https://osu.ppy.sh/beatmapsets/1405040#osu/2897630

We tried to update the map and was wrongly recognized as a different beatmap altogether instead of updating the current map. We asked GMT for support with this and removed the wrong set that was created, but we still can't update the original set. BeatmapID and BeatmapSetId keep getting changed to wrong values no matter what we do, so everytime we try to update the set it gets recognized as a new map and we can't update the original.

We've tried several things already:

 - Using an old backup as base and trying to update based on that.
 - Manually putting the correct BeatmapID and BeatmapSetID on the .osu files (changes to the one on the removed set no matter what we do)
 - Deleting the map, refreshing the beatmap list ingame (f5), and cleaning the SubmissionCache folder in the hidden data folder of the osu! install folder before updating.
 - Reinstalling the osu! client and trying a fresh upload.
 
 We got told to place the issue here hoping it can get resolved since we would like to avoid losing the mods already on the set. We think the web or the BSS still recognizes the map with the wrong ID somehow.

**Comment by peppy** [comment] 2021-03-30 00:13
Please upload the .osu files from your PC as well (in a zip file.

**Comment by Akareh** [comment] 2021-03-30 16:07
We managed to update the set by changing the diff names. 
Before the update, after the name change, the SetID and BeatmapID still changed to the deleted set. 

I'll send you the files I have from before the update this morning was made, since you might still want to check on this issue for other peeps. 

Reproduction steps that might help:
 - Nyukai was offline, and tried to update the set.
 - Was asked to login to complete the upload.
 - She logged in, uploaded the map and was wrongly recognized as a different set.
 
 We don't know where to find the network.log file, I'll upload it if we find it. 
[osu files.zip](https://github.com/ppy/osu-stable-issues/files/6230411/osu.files.zip)

Thanks for the help both from you and Death on this ^^

**Comment by peppy** [comment] 2021-04-08 08:16
Thanks for the extra information. This looks to be a duplicate of https://github.com/ppy/osu-stable-issues/issues/536, which was recently fixed (although the fix is only in cutting edge currently, I believe).

**Closed by peppy** 2021-04-08 08:16 UTC
