### ISSUE TITLE
In-game search let map "disappear"

### ISSUE THREAD

**Issue by Feerum** [ppy/osu-stable-issues#500] opened 2020-07-13 16:52 UTC
I just noticed some smaller bug which is a little bit annoying.

Whenever i use the in-game search for qualified beatmaps with "status=q" it shows me all qualified maps. So far so good.
Once i enter a beatmap to look at it and then quit the editor again, the map does not show up anymore. I have to change the search and then back to "status=q" for it to show up again. 

Pretty sure that's not intended behavior. I usually quit the editor to choose an other difficulty to open but the map is gone. 
That seem to happen with every qualified map you look up, so should be also easy to reproduce

**Comment by peppy** [comment] 2020-07-13 20:09
You mean opening the editor? Are you saving the map? If so, this is probably making local changes.

**Comment by peppy** [comment] 2020-08-10 04:40
Closing is intended behaviour.

**Closed by peppy** 2020-08-10 04:40 UTC
