### ISSUE TITLE
Editor timing tab: bpm change intervals should make sense

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-stable-issues#37] opened 2019-09-19 22:37 UTC
In the timing tab of the editor, if you click left and right arrows to adjust the bpm after tapping it out, it adjust by some decimal values.

The majority of popular songs are single integer BPMs, the editor encouraging decimal point timing by default makes it more likely for new mappers to miss-time maps from trying to use this tool and it throwing lesser used BPM intervals at them. Also the current .42 bpm being the "large" interval for changing BPM value is inconveniently small.

**Default** change amount should be **1** bpm.
Ctrl for **smaller** intervals should be adjusting decimal bpm like, tenths or one hundredths. Something actually useful. You basically never need to adjust by one thousandths. 
Shift for **larger** intervals should be by like **5** bpm, something actually large.

fwiw the F6 timing panel already defaults to the up/down arrows changing bpm in intervals of 1, making it much more convenient for adjusting timing once it's tapped out than the timing tab.

(posting cause i hope it'd be an easy fix by changing the values somewhere and this really sucks for usual timing use)

**Comment by peppy** [comment] 2019-09-20 04:14
Duplicate of #57. Fixed.

**Closed by peppy** 2019-09-20 04:14 UTC
Labels: easy fix

**Comment by iptq** [comment] 2019-09-20 11:42
whatever the fix for this was, it noticeably lags the game
