### ISSUE TITLE
Mod Leaderboards not working properly?

### ISSUE THREAD

**Issue by DatVeno** [ppy/osu-stable-issues#587] opened 2020-11-03 17:05 UTC
Mod leaderboards are really buggy since the recent update, it was perfectly fine before. 

Score on the bottom left is not showing anything, not even my top score. I have to go to global leaderboard first, then it loads in the top score.
![screenshot371](https://user-images.githubusercontent.com/38132190/98016869-c93c4100-1dfe-11eb-858c-1fde64a4745f.jpg)

Only my top score is showing even though I want to see my HDHR score on this one.
![screenshot368](https://user-images.githubusercontent.com/38132190/98017209-39e35d80-1dff-11eb-8e7f-acb33b8830bb.jpg)

In my opinion the change was really useless since it worked perfectly fine and how everyone else wanted it.

**Comment by peppy** [comment] 2020-11-04 00:53
The "change" was not "really useless" since it fixed another issue. What you mention is a regression and will be fixed in the next release.

**Comment by peppy** [comment] 2020-11-04 02:59
This should be resolved on cutting edge.

**Closed by peppy** 2020-11-04 02:59 UTC

**Comment by DatVeno** [comment] 2020-11-04 15:40
alright works perfect now, thank you!
