### ISSUE TITLE
Replay bug: Erroneously sliderbreaks

### ISSUE THREAD

**Issue by Phippe** [ppy/osu-stable-issues#195] opened 2019-10-30 18:08 UTC
When replaying my [play on Endless Tears](https://www.file-upload.net/download-13766842/Phippe-CLIFFEDGEfeat.NakamuraMaiko-EndlessTearsAIRakuensExtra2017-12-24Osu.osr.html), osu!stable sliderbreaks at around 400x, although the combo should get as high as 1000x. In osu!lazer it works correctly.

Video: https://streamable.com/vl5ak (1st one is stable, 2nd one lazer)

**Comment by Magnus-Cosmos** [comment] 2019-10-30 22:57
This is because your score was set in 2017, many changes to the client have been made since then, including a change to notelock. This is probably the cause if the replay inconsistency. The reason it doesn't happen in osu!lazer is because there is no notelock in osu!lazer

**Comment by smoogipoo** [comment] 2019-10-31 01:56
Likely very difficult to fix, marking as out of scope.

**Closed by smoogipoo** 2019-10-31 01:56 UTC
