### ISSUE TITLE
Can't place a red line with CTRL+P before any other red lines are placed

### ISSUE THREAD

**Issue by nl-tatatat** [ppy/osu-stable-issues#154] opened 2019-10-09 20:12 UTC
When I'm first timing a map my first instinct is to find the offset, and place a red line there with ctrl+p. I find the offest and press ctrl+p... and nothing happens! ctrl+p only works if there is already red lines placed. If you go into the timing menu and create a red line there, it overrides the offset to  0, not where you currently are in the timeline. You have to memorize/write down your current offset, and copy it into the timing panel.

Others and I would greatly appreciate being able to place the first red line at the correct offset, whether thats being able to press ctrl+p AND/OR adding a new red line in the timing panel and having the offset be where you are in the timeline.

**Comment by smoogipoo** [comment] 2019-10-10 01:02
Should be an easy fix.

**Comment by peppy** [comment] 2019-10-10 01:39
This is unintended behaviour, I think? Timing should be started by clicking the tap button, which will create a timing point for you. If a "red line" was created, it would set the BPM to some incorrect value and break the timing process from that point onwards.

**Comment by nl-tatatat** [comment] 2019-10-10 04:00
nobody/not many people time that way anymore, peppy. The tap for bpm is largely ignored. Finding the offset first is the most important step, and then lining up the bpm with the next audible sound. 
What I and others do is place the red line/uninherited timing point first at the correct offset with a guesstimate bpm. and then adjust the bpm to line up with the song.

Tap for bpm is just too inaccurate and messes with the offset to much to seriously use.

**Comment by peppy** [comment] 2019-10-10 04:07
If anything, the tap mechanism should be improved rather than making hacks around it. There should only be one path for timing a beatmap.

**Comment by nl-tatatat** [comment] 2019-10-10 04:08
The tap mechanism isn't perfect, and never can be. Humans are inconsistent at tapping. Perfect bpm is required for beatmaps

**Comment by nl-tatatat** [comment] 2019-10-10 04:11
Also sometimes you already know the BPM. Like the bpm is advertised somewhere, or the song has already been mapped in another capacity. Why tap for bpm when you already know it? Just place down an inherited timing point and use the right bpm.

**Comment by peppy** [comment] 2019-10-10 04:22
It's not supposed to be perfect. It's supposed to be the first step. Not manually aligning an offset then adjusting BPM from 120.

**Comment by peppy** [comment] 2019-12-13 03:01
Thanks for the suggestion.

As we only have a limited amount of development time focused on osu-stable changes, we have deemed this out of scope of the fixes we are able to apply. It  will likely be (or already has been) solved in [osu!lazer](https://github.com/ppy/osu).

**Closed by peppy** 2019-12-13 03:01 UTC
Labels: easy fix, will investigate
