### ISSUE TITLE
Stacking in editor is kind of broken from recent updates

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-stable-issues#279] opened 2019-12-22 19:34 UTC
the snap to stack feature is having significant problems as of recent update. (https://osu.ppy.sh/home/changelog/stable40/20191220.2)

It causes notes to "spaz" between stacked an unstacked states, making it rng whether the final result will be stacked or not when a mapper lets go of the circle.
This is especially causing difficulties in stacking more than 2 objects, where 3 objects may appear to be just 2 stacked, and 4 may appear to be 3, etc etc. This is a significant concern because the broken stacking appearances are carrying over to gameplay as well, effectively hiding notes in the stack.

A significant number of mappers are having issues with this right now and are frustrated with how it's not functioning nearly as well as it before. Stacking circles under slidertails is especially working poorly now.

Video:
https://www.youtube.com/watch?v=FV_dIZmcGkg

**Comment by smoogipoo** [comment] 2019-12-23 03:52
Fixed in the latest cutting edge.

**Closed by smoogipoo** 2019-12-23 03:52 UTC

**Comment by dorothy3242** [comment] 2019-12-23 04:28
After checking this update out: it seems to be working perfectly if you move the earlier objects on top of later objects, but is still having the same issues if you try to put later objects under earlier objects. 

As most mapping happens by placing earlier objects first and then going later in time from there, from there I can see why most people are having issues with this.

Video 2:
https://www.youtube.com/watch?v=bDWQDIF7Y-w

**Comment by peppy** [comment] 2019-12-23 04:33
Please include the .osu you are testing with. I cannot reproduce in my own testing.

**Comment by dorothy3242** [comment] 2019-12-23 04:37
https://pastebin.com/65iKhXDw

I just added 3 circles at a random time to illustrate this, they're at 02:09:168 - 

the order the objects are moved in is key here I think since if you move 2 on top of 3, and then 1 on top of 2 it works perfectly, but if you move 2 under 1 and 3 under 2 it gets wonky
