### ISSUE TITLE
why isn't fix

### ISSUE THREAD

**Issue by NamOpt** [ppy/osu-stable-issues#1232] opened 2024-04-23 01:29 UTC
![image](https://github.com/ppy/osu-stable-issues/assets/120299835/b369f7fd-73f8-4dda-afb9-a3ca4b77bdb2)
the background show the seasonal background, not beatmap background, always show

**Comment by peppy** [comment] 2024-04-23 01:45
The backgrounds must be missing on disk. Did you delete them somehow?

**Comment by NamOpt** [comment] 2024-04-23 02:02
nope

**Comment by peppy** [comment] 2024-04-23 05:14
Something else on your PC must have. Please check on the files.

**Comment by NamOpt** [comment] 2024-04-24 04:36
i checked
the file is not deleted
![image](https://github.com/ppy/osu-stable-issues/assets/120299835/16b85612-22f0-4f99-a962-2f1a753a307b)

**Comment by peppy** [comment] 2024-04-24 04:47
i'm not sure sorry. you're not giving enough information and this isn't a tech support forum. the beatmap works fine for me on a fresh download.

**Comment by NamOpt** [comment] 2024-04-25 02:11
but... i need to giving u enough information?
okay, let question me and ill giving u information

**Comment by Joehuu** [comment] 2024-05-04 21:51
Duplicate of https://github.com/ppy/osu-stable-issues/issues/282 / https://github.com/ppy/osu-stable-issues/issues/1035, which should be closed because of https://github.com/ppy/osu-stable-issues/issues/1035#issuecomment-1249970775.

**Closed as completed** 2024-06-06 14:23 UTC
