### ISSUE TITLE
map uploading bug

### ISSUE THREAD

**Issue by dobulu** [ppy/osu-stable-issues#663] opened 2021-02-08 13:25 UTC
Try Auto my map just after uploading then immediately finished with 0 score or combo but 100% acc. After that I go to editor again finding that I can't edit it cause always teleported to the not mapping part.
 [https://osu.ppy.sh/ss/16184687/d2f2](url)

**Comment by peppy** [comment] 2021-02-13 15:16
We can't really help you at all unless you link or attach your beatmap. I'm going to close this issue as it's likely a user mistake and not a bug, but feel free to provide more information and someone will look into your issue in more detail.

**Closed by peppy** 2021-02-13 15:16 UTC
