### ISSUE TITLE
Small Lag Spikes during gameplay

### ISSUE THREAD

**Issue by Mysidian** [ppy/osu-stable-issues#816] opened 2021-08-14 15:20 UTC
During short and long osu sessions, sometimes I got some microstuttering/small lag spikes, idk why this happens, no third-party apps, no google chrome no discord, lastest osu stable version, updated nvidia drivers, etc etc...

thx for helping

Posted some options in this image

![image](https://user-images.githubusercontent.com/82321696/129451003-89aecb3e-3758-4989-bd52-b226236c2316.png)

and this is a video about the issue

https://user-images.githubusercontent.com/82321696/129450935-3df97868-c92a-4df7-977f-9ce99d72c971.mp4

**Comment by peppy** [comment] 2021-08-15 17:52
Please run under cutting edge and turn on performance logging in settings, then send your performance.log files (there may be several of them) after this happens.

**Comment by Mysidian** [comment] 2021-08-17 17:33
Sorry for late, this is what I have on performance.log files

[performance.log](https://github.com/ppy/osu-stable-issues/files/7001900/performance.log)

**Comment by peppy** [comment] 2021-08-25 13:46
The attached performance log only shows you being at the menu. Are you sure you didn't restart osu! after reproducing the issue? The logs are cleared each time you start the game.

**Comment by AriizuCA** [comment] 2022-02-27 23:06
Hi, I am also having a similar issue and would like some help with how to fix it.  Cross posting this from the [osu! forums](https://osu.ppy.sh/community/forums/topics/1527535?n=1) since it isn't gaining any traction.

**Problem Details:**
I've been noticing an increase in spiked frames while playing.  These spiked frames can be severe enough to easily break combo at random intervals.  Under "Video or screenshot showing the problem," these are the videos of the worse spikes which would easily break combo.  While playing, there are also many micro spikes which are noticeable but do not impede gameplay that were not recorded.
I switched to Cutting Edge in order to generate a [performance log](https://cdn.discordapp.com/attachments/673783701905342494/945813104380485692/performance.log) for the play session and noticed a decrease in the severity of the spiking issue; on stable I would experience sometimes a [full second or two](https://www.twitch.tv/videos/1293019763) of spiked frames and scores wouldn't submit because of it.  Frequency of spikes are still an issue though and has been ongoing for at least a couple of months with it becoming more common lately.
Any help is appreciated!

**Computer Specs:**
Processor: Ryzen 7 5800X
GPU: GeForce RTX 3080
RAM: 32 GB (2 x 16 GB) DDR4
OS: Windows 10 Home 10.0.19043 Build 19043

**Programs Running While Playing/Streaming:** (I kind of need these to be running for my stream setup)
Chrome
[OBS](https://obsproject.com/)
[gosumemory](https://github.com/l3lackShark/gosumemory)
[osu!StreamCompanion](https://github.com/Piotrekol/StreamCompanion)
[KeyOverlay](https://github.com/Blondazz/KeyOverlay)
Streamlabs Chat Bot
[Snaz](https://github.com/JimmyAppelt/Snaz)
[chatterino](https://chatterino.com/)
[Discord](https://discord.com/)

**Some Solutions I've tried:**
[osu! wiki Performance Troubleshooting](https://osu.ppy.sh/wiki/en/Performance_troubleshooting)
[osu! - How To Fix Lag Spikes & Stuttering](https://www.techy.how/tutorials/osu-fix-lag-spikes-stuttering)
[How to Make osu! Run Better: The Basics](https://www.youtube.com/watch?v=YzcyGZ1jFag&list=PLmBBXZ9yma48Qs02s30b6Budw1q2D8Pum&ab_channel=Jaymusta)

**Video or screenshot showing the problem:**
These videos are from February 21st, 2022 and document a majority of the spiked frames that I experienced throughout the play session along with timestamps synchronized with the uptime counter in the top right.
[00:25:22](https://www.twitch.tv/videos/1306294411)
[00:29:49](https://www.twitch.tv/videos/1306294410)
[01:39:31](https://www.twitch.tv/videos/1306300257)
[02:12:46](https://www.twitch.tv/videos/1306300255)
[02:22:34](https://www.twitch.tv/videos/1306300258)
[02:47:26](https://www.twitch.tv/videos/1306300260)
[03:41:50](https://www.twitch.tv/videos/1306300254)
[04:07:46](https://www.twitch.tv/videos/1306300259)

**osu! version:** Cutting Edge 20220221

**Comment by timelessnesses** [comment] 2022-02-28 00:42
maybe try stable version first?

**Comment by AriizuCA** [comment] 2022-02-28 01:17
I'm uncertain if stable generates a performance log like cutting edge does.  Stable also was what I've been running most of the time, but has been the worst offender for the spiked frames in terms of length that the frames freeze.  Only switched to cutting edge for the last week since it is slightly more stable with the spiked frames.
[This happened](https://www.twitch.tv/videos/1293019763) while on stable and I had several other moments where the game would seemingly freeze up for more than a second, causing scores to no longer be submitted even after I completed a map.  In those cases, I wouldn't die in game even if there should have been notes while the longer spike plays out.  The game would just continue normally after frames return and HP would not drop.  On the one's that I could recover on and pass the map, I would get an error message and not see the score submitted on the leaderboards, as if the score was an offline play or something and score would remain in locals.  I do not have these moments documented, but they happened within the last month, and it happened twice before switching to cutting edge.  It might take time to find if they are important enough to find.

**Comment by smoogipoo** [comment] 2022-02-28 03:05
A few ideas:
- Do you have Steam running?
- Were you playing another game prior to starting osu! such as Valorant, Apex Legends, or Fortnite?
- Tried closing Discord?
- Tried closing web browsers?
- Tried restarting your PC and running osu! immediately?

**Comment by AriizuCA** [comment] 2022-02-28 07:24
After playing for several hours:
Steam was not running in the background so no issue there.
No prior games were played before hand.
Closed Discord but still got a frame spike.
Closed Chrome & Discord and still got a frame spike.
Restarting and running osu! immediately, with no other programs running aside from some that get minimized to system tray (Nvida settings/ShareX/etc.), got a single spike frame at the start of one map.  Overall though, no micro spikes, game played very smooth, and that one spike frame at the beginning of the map might have been a loading issue.  [Performance.log](https://cdn.discordapp.com/attachments/673783701905342494/947755120249167882/performance.log) from after restarting PC.

**Comment by peppy** [comment] 2022-02-28 08:34
Can you elaborate on how the final test went smooth vs the two before it? I'm a bit confused as to how you're testing there. If the restart was the only difference, can you also try after a restart with discord/chrome still open and confirm it's still smooth?

If that's the case, keep track of what you are doing after the restart until the lag starts to occur again (to the best you can). Things like putting the PC to sleep, locking it, running certain games. If we can isolate this down to something that's happening on your PC which triggers the lag permanently from that point onwards, we may be able to find a solution (for either just you or something more universal).

I'm also interested to know whether switching compatibility mode on after the lag spikes start helps at all. This will force the game to use DirectX, which we've found to be more resilient to external factors than OpenGL.

**Comment by AriizuCA** [comment] 2022-02-28 08:43
To elaborate on why the game was more smooth after restarting PC.  All of these tests have been ran with Unlimited Gameplay enabled.  The counter at the bottom right corner of the screen hovered around 0.4-0.5ms directly after restarting with no other programs opened.  When Chrome or Discord were opened, the game ran between 0.8-1.2ms with a lot more fluctuation.  Running in Optimal also capped the game to 1.2ms.

Normally when I play osu!, it will be near the end of the day after my PC has been running for 12+ hours so not sure if that might cause issues.  I have tried compatibility mode before but will test again tomorrow.

**Comment by peppy** [comment] 2022-02-28 08:58
I'd highly recommend you don't run unlimited when testing this stuff. Or ever. Because it is known to *add* stutters caused by excessive garbage collection or GPU overloading.

Will wait to hear back on your subsequent results. Very likely that something is getting your system or GPU into a suboptimal state, by the sounds of it.

**Comment by AriizuCA** [comment] 2022-03-01 05:34
Tested different settings to see if anything changes:  (all these configurations are without restarting my computer as I wanted a standard baseline for testing)

Cutting Edge, Optimal, All Apps (standard configuration for stream)
- 3 spiked frame moments within an hour.

Cutting Edge, Optimal, Compatibility Mode, All Apps
- 3 spiked frame moments within half an hour.
- I also noticed that if I pause, alt-tabbed, and then returned to the play, the game would have a massive spiked frame and this was replicable.

Cutting Edge, Optimal, Minimum Apps Opened (Included Twitch Chat, OBS)
- 7 spiked frame moments within 45 minutes.

Cutting Edge, Optimal, Compatibility Mode, Minimum Apps Opened
- 1 spiked frame moment, though I ran out of time and was only able to run the game in this configuration for 20 minutes.

One of my viewers also suggested running the Ctrl+F11 graph which I was only running for the last configuration.  Mostly appeared normal, though occasionally white tick spikes would appear on the graph.  We discovered that these white ticks were caused by my keypad.  Not sure if that is contributing to the issue but thought that I should note it.

**Comment by peppy** [comment] 2022-03-01 11:06
If you can confirm that all spikes are white, and you can find the cause of the white spikes then you have found your issue.

**Comment by AriizuCA** [comment] 2022-03-01 21:24
I'm not sure if the white spikes on the Ctrl+F11 graph are what is causing the spiked frames.  They show up frequently on the graph, about 1-2 every second, and I didn't experience any spikes while the graph was open.  This was due to testing for around 10 minutes before I had to stop streaming.

[Here is a clip](https://www.twitch.tv/videos/1412369837) showing the white spikes on the graph for clarification.  There is a break in the map and no white ticks appear since I am not tapping on my keyboard.

Will do more tests with the Ctrl+F11 graph open later today.

**Comment by AriizuCA** [comment] 2022-03-02 09:07
This time I tested with the original first setup of **_Cutting Edge, Optimal, and All Stream Apps_** for a period of three hours while having the Ctrl+F11 graph open.  What I noticed is that in the moments that laggyness or spiked frames occurred, the graph would either stagger or nearly stop in movement.  This also happened when I was not getting good accuracy on a stream, so not sure if the issue is also tied to the sudden rendering of many 100's and 50's or that may be another cause to be looked into.  Here is the [performance log](https://cdn.discordapp.com/attachments/673783701905342494/948504826084458507/performance_ariizu_cuttingEdge_optimal__allApps_Mar01.log) for the session.

I've clipped the instances where the graph was behaving in a weird way.  During this three hour stream, I had 31 moments where frames were dropped from a variety of different severities.  Most of the dropped frames were minimal frame drop moments which were recoverable or barely even noticeable.  Eight moments were high frame drop moments which were recoverable but very noticeable.  Three moments were spiked frames which were not recoverable and would guarantee a miss.

**Minimal Frame Drop Examples:** (6)
[00:42:49](https://www.twitch.tv/videos/1412866345)
[00:44:18](https://www.twitch.tv/videos/1412866352)
[00:46:53](https://www.twitch.tv/videos/1412866350)
[01:20:52](https://www.twitch.tv/videos/1412866346)
[01:22:36](https://www.twitch.tv/videos/1412866343)
[01:43:48](https://www.twitch.tv/videos/1412866337)

**High Frame Drop Examples:** (8)
[00:10:47, 00:10:53](https://www.twitch.tv/videos/1412866347)
[00:32:35](https://www.twitch.tv/videos/1412866333)
[01:18:57](https://www.twitch.tv/videos/1412866338)
[01:50:22](https://www.twitch.tv/videos/1412866332)
[01:54:05](https://www.twitch.tv/videos/1412866339) Here is the low accuracy stream where the frames dropped considerably.
[02:27:07](https://www.twitch.tv/videos/1412866348)
[02:47:09](https://www.twitch.tv/videos/1412866335)

**Spiked Frames Examples:** (3)
[01:18:43](https://www.twitch.tv/videos/1412866336)
[01:44:26](https://www.twitch.tv/videos/1412866344)
[02:27:17](https://www.twitch.tv/videos/1412866340)

I would also like to note that I did have an [issue in the past](https://osu.ppy.sh/community/forums/topics/1052959?n=1) where the graph did a similar movement with frame issues and that was resolved by adjusting the polling rate of my mouse from 1000 Hz to 500 Hz.  It is still at the 500 Hz setting due to that and I had tried adjusting the polling rate weeks ago (before implementing cutting edge or optimal, or after reviewing that the graphs were doing the same thing in todays stream) with it not fixing the spiked frames.  May have to adjust the polling rate again tomorrow to see if it changes anything with cutting edge and optimal enabled.

**Comment by peppy** [comment] 2022-03-02 16:20
Thanks for the reports, these are useful. I'll go through them and see if there are any issues that could potentially be improved from our end.

But also let me say that.. I feel to some extent as a developer that we are in the position to only fail. Each of the external applications you are running on stream are likely rendering via webkit, which is known to cause issues when run adjacent to 3d apps. In addition, they are reading from the process memory, which could also potentially cause issues.

I know we've already covered this but I just want to reinforce that this is very hard for us to do well at. Many people claim that "other game does fine", but that may just well be that when playing the other game there are less things interacting with it, as most games prohibit the kind of interactions that osu! is allowing.

Quite frustrating from our perspective, so thought I'd detail this.

Shouldn't need further details for now, will go through your logs over the next days.

**Comment by peppy** [comment] 2022-03-02 18:30
@AriizuCA I've pushed a release to cutting edge with some initial changes that I'd like you to test. I have no idea whether it will solve your specific issues, but reading through your log it may help with a couple of spikes.

Note that it may also do nothing.

This will only have effect during gameplay. I've noticed you get a lot of spikes at song select and results screen, but these are unrelated to what I'm looking at for now.

**Comment by AriizuCA** [comment] 2022-03-03 06:58
First off, I would like to thank you for taking the time out of your schedule to help me with this issue.  If the main culprit is a third party application, then that is completely out of your control and I would never place blame on you for that.  If it is a third party app, then I definitely want to help narrow down which one it is and have it documented so that others who might have a similar problem have an idea as to what might be causing it.  It's just that I'm not too knowledgeable on this kind of stuff and most of my problem solving has been through brute force, so this thread has helped narrow down the issue a bit.

Testing today, I tried two different configurations on the latest update for Cutting Edge.  Bad news was that it did not seem to change much with the spikes for the configuration of Cutting Edge, Optimal, and All Stream Apps (3 spiked frames in 50 minutes) as well as Cutting Edge, Optimal, Compatibility Mode, and All Stream Apps (2 spiked frames within 25 minutes).

Performance Logs for these sessions if you needed them:
- [Cutting Edge, Optimal, and All Stream Apps](https://cdn.discordapp.com/attachments/673783701905342494/948826860068945930/performance_ariizu_cuttingEdge_optimal__allApps_Mar02.log)
- [Cutting Edge, Optimal, Compatibility Mode, and All Stream Apps](https://cdn.discordapp.com/attachments/673783701905342494/948827683184332840/performance_ariizu_cuttingEdge_optimal_compatibilityMode_Apps_Mar02.log)

Some good news though, was when I was running a barebones stream set up with the bare minimum apps (OBS, Chatterino (twitch chat), osu!, and my stream timer) on Cutting Edge and Optimal.  The other day, it seemed that even if I was running this set up, I would still get spiked frames.  Today, I ran this set up for nearly two hours without seeing any spiked frames, much less any minimum frame drops.  After that, I tested with all apps relaunched and also did not get any frame rate loss for twenty minutes before I had to end stream.

Performance Log for Lagless Session:
- [Cutting Edge, Optimal, Minimum Apps/All Apps (for last 20 minutes)](https://cdn.discordapp.com/attachments/673783701905342494/948826859506900992/performance_ariizu_cuttingEdge_optimal__allAppsOpenedAfterOsu_Mar02.log)

This makes me wonder if launching osu! before any of the stream apps changes priority for how processes are handled for computer resources.  Either way, it seems that one of the streaming apps that I am using is the culprit.  Not 100% sure since this is the first session where the frame drops seemed to not exist after relaunching apps, but that was also for a small period of time so I will test this tomorrow.

**Comment by peppy** [comment] 2022-03-03 07:00
Launching osu! first could potentially cause apps that were hooking on new application launch to not "see" osu!. Not sure if that's what's happening, but it's a theory. If you can continue to test one change at a time and figure which application is responsible we can probably take things further.

**Comment by AriizuCA** [comment] 2022-03-04 08:47
[**Configuration 1**]  So I tried running the game first then all the stream apps after and still had spiked frames (2 within 25 minutes).  This was to test if it mattered what order the game and apps were opened, which doesn't seem to be the case.  Will leave performance logs for each session if they matter at all.
- [Performance Log for All Stream Apps Session (2 Spikes, apologies if the naming scheme is kind of ugly)](https://cdn.discordapp.com/attachments/673783701905342494/949218880147034122/performance_ariizu_cuttingEdge_optimal__allAppsOpenedAfterOsu_Mar03.log)

[**Configuration 2**]  Restarted the game first and then ran with Discord, Chrome, and the bare minimum of streaming apps to see if anything would change.  Had no frame drops in a 45 minute period.
- [Performance Log for Discord/Chrome + Bare Minimum Stream Apps (No Spiked Frames)](https://cdn.discordapp.com/attachments/673783701905342494/949219225321504778/performance_ariizu_cuttingEdge_optimal_DisChrChaTTSSNaOBS_Mar03.log)

[**Configuration 3**]  Restarted the game again, leaving all previously opened apps active while also adding gosumemory.  This was to see if one of the apps that directly interacts with the game was causing the problem.  No frame drops for 50 minutes.
- [Performance Log for Configuration 2 + gosumemory (No Spiked Frames)](https://cdn.discordapp.com/attachments/673783701905342494/949219476136677426/performance_ariizu_cuttingEdge_optimal_DisChrChaTTSSNaOBSGosu_Mar03.log)

[**Configuration 4**]  Restarted game, closed gosumemory, and started StreamCompanion with the same though that maybe since it interacts with the game, that it could be the source of the spiked frames.  Had no frame drops in 50 minutes.
- [Performance Log for Configuration 2 + StreamCompanion (No Spiked Frames)](https://cdn.discordapp.com/attachments/673783701905342494/949220120910262312/performance_ariizu_cuttingEdge_optimal_DisChrChaTTSSNaOBSStrmComp_Mar03.log)

[**Configuration 5**]  Restarted game and had both gosumemory and StreamCompanion run at the same time with the second configuration of apps.  The thought was, maybe the two apps aren't behaving well together.  No spiked frames in a 45 minute period.
- [Performance Log for Configuration 2 + gosumemory + StreamCompanion (No Spiked Frames)](https://cdn.discordapp.com/attachments/673783701905342494/949221018600362014/performance_ariizu_cuttingEdge_optimal_DisChrChaTTSSNaOBSStrmCompGosu_Mar03.log)

[**Configuration 6**]  Restarted game and added the keyoverlay along with all of the previously used apps in the previous configuration.  This test lasted 30 minutes and no spiked frames were detected.
- [Performance Log for Configuration 5 + keyoverlay (No Spiked Frames)](https://cdn.discordapp.com/attachments/673783701905342494/949222411847499866/performance_ariizu_cuttingEdge_optimal_DisChrChaTTSSNaOBSStrmCompGosuKeyOver_Mar03.log)

I do find it strange that initial launching of the game as well as applications for streaming are causing spiked frames, but as soon as I restart them all, the spiked frames disappear.  I might need to just keep running the game when it spikes and then close each app one by one to see if that helps determine which one is causing the issues.

In the end, restarting the game and apps after initial launch does seem to solve my initial issue in a roundabout way.  Long term testing is still required to confirm this as most of the tests that I've done are with different configurations that only last about an hour.  I would like to see how stable the resetting method is after 2-3 hours of gameplay.  So tomorrow, I can test that or keeping the game open and closing individual apps over time while the spiked frames are happening.

**Comment by AriizuCA** [comment] 2022-03-05 07:16
Updated to latest version of [Cutting Edge](https://osu.ppy.sh/home/changelog/cuttingedge/20220304) (not sure if there was a change like the previous patch for this issue) and did not experience any spiked frames in todays stream with all my normal applications opened.  Gameplay lasted for around 3.5 hours without any spiked frames.  Here is the [performance log](https://cdn.discordapp.com/attachments/673783701905342494/949563310431432744/performance_ariizu_cuttingEdge_optimal__allAppsOpenedAfterOsu_Mar04.log).

Did notice that StreamCompanion doesn't see osu! so it wasn't working.  Looked back at previous streams and noticed that it hasn't been working since March 2nd, I only every use it to display real-time UR.  TheMad_N's comment on the [previous patch notes](https://osu.ppy.sh/home/changelog/cuttingedge/20220303) seems to confirm a similar issue.  Not 100% sure that it was StreamCompanion causing the spikes since I was still able to have spiked frames in the last two days with it not working.  However, gosumemory, a very similar type of application, does work so not really sure why StreamCompanion broke.

Will stream again with the same configuration I had today to see if I can have 2 days in a row where no spiked frames occur.

**Comment by AriizuCA** [comment] 2022-03-07 07:14
Still no spikes during stream for a three hour period.  I asked a friend, who doesn't stream but was also experiencing spiked frames, and they said that their spiked frames have also disappeared in the last couple of days.  I think whatever change that took place has resolved the spiked frame issue.  Will report back in a week to confirm for certain that the spiked frames are gone.  Thank you once again peppy for resolving this.
- [Performance Log for the Day](https://cdn.discordapp.com/attachments/673783701905342494/950281974776496178/performance_ariizu_cuttingEdge_optimal__allAppsOpenedAfterOsu_Mar06.log)

**Comment by peppy** [comment] 2022-03-07 07:33
Great to hear. As a heads up, the windows key blocking changes have been rolled out to stable now.

**Comment by AriizuCA** [comment] 2022-03-13 20:22
So after testing for a week on stable, I've not experienced any spiked frames outside of when a new StreamCompanion update occurred.  This update [v220309.20](https://github.com/Piotrekol/StreamCompanion/releases) states in the patch notes that it "fixed" the memory reading of IsReplay flag completely breaking SC (StreamCompanion) after latest osu! update.  After testing with the latest version of StreamCompanion, the spiked frames returned.  It is easy enough to not stream with StreamCompanion, but it does seem like the largest source of the spiked frames were due to it.

Not all the frame rate issues were StreamCompanion alone, since small drops in frames also used to happen even with StreamCompanion off, so the changes made in this thread have improved stability significantly for framerate for myself and hopefully for others who might have experienced similar issues.  Once again, thank you for the help!

**Comment by peppy** [comment] 2022-03-14 05:06
Thanks for the update. Are you planning on reporting the issue to stream companion's dev? It would be good to have an issue to link to so we can add this to our performance troubleshooting guide (https://osu.ppy.sh/help/wiki/Performance_Troubleshooting) suggesting people disable that app until it's confirmed it doesn't cause issues.

**Closed by peppy** 2022-03-14 05:06 UTC

**Comment by stevefan1999-personal** [comment] 2023-09-03 06:59
I also wanted to point out that I have a consistent lag spike on my Ryzen 3700X if I'm running memory hungry applications alongside osu like Edge (excuse me but I have 300 tabs).

My guts feelings pointed me to specific CPU configuration issue. As I'm running a 3700X it is a Zen 2 architecture, but for Zen architecture in general, memory access between CCX (think of it as a tiny NUMA cluster inside the same CPU package) have significant penalties due to cache coherence and synchronization.

So, for latency intensive software like DAWs and games especially rhythm games, it is strongly advised to schedule the program and the memory on the same CCX, but if you have another program that takes a huge chunk of memory, it is highly possible that the memory could be spilled all over different places, making memory scheduling difficult and often stored on non-optimal locations, hence the lag spikes.

This is so annoying on stable as I have to either drop my tabs from 300 to 60, or close the Edge browser entirely, but apparently the issue is gone on lazer.
