### ISSUE TITLE
Editor : bugs upon reaching outro

### ISSUE THREAD

**Issue by xenallio** [ppy/osu-stable-issues#304] opened 2020-01-04 18:26 UTC
Upon reaching the outro (which you do by going to the end of the song and hit play, after which it says "outro" in bottom left), you cannot do the following:
- Use hotkeys to move timeline
- Scroll the timeline
- Click in the timeline
- Press Z (place cursor at the begenning of the map)

All of thoses will simply replace the cursor back to the outro in the next frame

If you press play after reaching outro, the time will still run without map/audio and [the cursor just walks away](https://gyazo.com/2ef3a71656da8bd7cccb3eb53e0dfa72). After this, if you move in the timeline in any ways, it will place you back to the begenning of the song, regardless of the action you've done to do so (aka pressing in the timeline will not go to the location)

Occurs since last update (going to say since 20200103.3, since the next updates were just audio fixes)

Source : https://osu.ppy.sh/community/forums/topics/1006394

**Comment by xenallio** [comment] 2020-01-04 18:29
I'm blind, kinda dupe of https://github.com/ppy/osu-stable-issues/issues/301 but with more explaination. Will leave open for visibility and let people decide which to keep.

**Comment by peppy** [comment] 2020-01-09 02:54
Closing as duplicate of #301.

**Closed by peppy** 2020-01-09 02:54 UTC
