### ISSUE TITLE
[Cutting Edge] Screen goes black with music still playing when navigating to Edit mode or when changing from Fullscreen (render at native) to Non-fullscreen

### ISSUE THREAD

**Issue by Skubers** [ppy/osu-stable-issues#946] opened 2022-03-01 13:14 UTC
I'm attaching a video of both issues and logs

For the first issue, you can get the screen back if you Esc your game back to Main Menu and Alt+Tab (as presented in the video)

https://user-images.githubusercontent.com/82095491/156175375-0743a5c9-6a2c-4d91-8390-7fd63a56a357.mp4

And here's the second issue

https://user-images.githubusercontent.com/82095491/156175406-7d37da1d-341f-41af-bea5-57a2ad54c72d.mp4

Sorry for recording with a phone, I couldn't get OBS to capture everything

[Logs.zip](https://github.com/ppy/osu-stable-issues/files/8161816/Logs.zip)

**Comment by peppy** [comment] 2022-03-01 13:21
Fuck everything.

Can you confirm this doesn't happen on stable?

**Comment by Skubers** [comment] 2022-03-01 13:24
On Stable only the changing from Fullscreen to Non-fullscreen black screen repros. The first part of the issue doesn't appear

**Comment by peppy** [comment] 2022-03-01 13:29
Can you describe in more words which is the "first" and "second" issue? I've watched your videos but would appreciate a bit more explanation. Specifically, what is broken on stable, and what is broken on cutting edge.

**Comment by Skubers** [comment] 2022-03-01 13:39
Stable - Switching from Fullscreen (Render at Native) to Non-Fullscreen is broken

Cutting Edge - Switching from Fullscreen (Render at Native) to Non-Fullscreen is broken AND Screen goes black when navigating to Edit mode

**Comment by peppy** [comment] 2022-03-01 13:45
What's your GPU and windows version?

**Comment by Skubers** [comment] 2022-03-01 13:46
[DxDiag.txt](https://github.com/ppy/osu-stable-issues/files/8161975/DxDiag.txt)
Here's my DxDiag, OS build is Win 10 21H2 (19044.1566)

**Comment by evilldev** [comment] 2022-03-01 14:39
I'd just like to add that this happens to me too on the latest cutting edge version. Opening the editor makes the screen go fully black.

Using Win 10 21H2 (19044.1566) with a GTX 1060 6GB (driver version 511.65)

E: The problem seems to be fixed if I set my portrait monitor to be landscape instead

**Comment by peppy** [comment] 2022-03-01 14:41
Can you show the display settings layouts which cause issues and also the ones which don't?

**Comment by evilldev** [comment] 2022-03-01 14:56
It seems like this happens only if the second monitor is in portrait mode, like this:
![image](https://user-images.githubusercontent.com/19711659/156191877-17fc0291-974e-47ae-bd69-52dcd12cccb3.png)

It doesn't seem to be an issue when both monitors are in portrait mode, however. I tried to change the resolution but that didn't change the end result in any way either.

**Comment by Skubers** [comment] 2022-03-01 14:57
I'll check out on my setup later, after work

**Comment by Skubers** [comment] 2022-03-01 15:23
Okay, I've did some tests:
I've turned on Compatibility Mode and the issue was gone completely
I've turned if off and checked various in-game resolutions and osu! display settings combinations. On all of them the issue reproduced
I've removed my second monitor, and the bug stopped reproducing.
I've turned my second monitor back on, and now for some reason I can't reproduce the bug anymore. 

Feels like it had some 'thing' turned on which turned itself off when I've removed my second monitor

**Comment by peppy** [comment] 2022-03-01 15:29
It's always only affected things with compatibility mode off, and only with dual monitors. Thanks for the layout image, I will try and reproduce the issue.

**Comment by Kominaru** [comment] 2022-03-02 23:10
Having a similar issue with a more "standard" dual monitor setup, since some stable updates ago (around september?). My main monitor (1920x1080) is running osu, the other one being 1680x1050. Screen blacks out completely upon opening the editor for one map or clicking the osu logo then "Edit" in the main nenu. The issue is also reproducible on Cutting Edge. 

I'm running a RTX 2060 on Windows 10.0.21387 

![](https://user-images.githubusercontent.com/43741444/156464510-daf3632d-bd64-4d05-a187-815803b7cb36.png)

**Comment by peppy** [comment] 2022-03-05 16:17
Thanks, I was able to replicate this and have a second fix on the latest cutting edge release. Please give it some testing.

**Comment by Skubers** [comment] 2022-03-05 16:24
I've attempted to check the fix. Everything looked fine, but after a couple of retries i've been able to reproduce the Fullscreen-Nonfullscreen issue

**Comment by peppy** [comment] 2022-03-05 16:36
Can you explain what you mean by "a couple of retries"? What is your process?

**Comment by Skubers** [comment] 2022-03-05 16:52
I've updated my game from stable to cutting edge, did like 6 tries of going fullscreen - non-fullscreen (same settings as before, nothing was changed). Nothing happened which is good. I've then navigated to Edit mode and the into Editor like 3 times, same situation here, nothing happened. Then for good measure I've tried the Fullscreen - non-fullscreen stuff 3 times and on 3rd try, my game stayed black when I've switched (i believe) from non-fullscreen to fullscreen.
So I'd say the bug is fixed mostly, but there is still a possibility

**Comment by Kominaru** [comment] 2022-03-05 19:28
> Thanks, I was able to replicate this and have a second fix on the latest cutting edge release. Please give it some testing.

Looks fine now in my end (the instance where it blacked out when opening editor). Thanks for fixing this

**Comment by peppy** [comment] 2022-03-07 04:11
Going to close this for now as I think we are doing the best we can to fix this issue. I've tried to reproduce the occasional failure mentioned above but can't seem to. I also can't think of how it could be occurring. Not to say it isn't, but it's probably rare enough that we can ignore it for now.

**Closed as completed by peppy** 2022-03-07 04:11 UTC
