### ISSUE TITLE
Freezes while searching beatmaps.

### ISSUE THREAD

**Issue by potato4444** [ppy/osu-stable-issues#222] opened 2019-11-24 03:45 UTC
When I search for a map at the beatmap select screen the game will freeze for a few seconds, often while I'm in the middle of typing. You will notice several times in the attached performance log that there are several frames that are 2.5 seconds long.
[network.log](https://github.com/ppy/osu-stable-issues/files/3883182/network.log)
[performance.log](https://github.com/ppy/osu-stable-issues/files/3883183/performance.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/3883184/runtime.log)
[update.log](https://github.com/ppy/osu-stable-issues/files/3883185/update.log)
[update_success.log](https://github.com/ppy/osu-stable-issues/files/3883186/update_success.log)

These freezes are new (I wasn't getting them a month ago).

Just in case it is relevant, the number of beatmaps i have is about 4500 difficulties.

**Comment by peppy** [comment] 2019-11-24 03:48
Checking your logs, this is just osu! searching for beatmaps. Is that "4500" number what it says at the main menu?

**Comment by potato4444** [comment] 2019-11-24 03:52
No, that 4500 was me adding up the number of maps in my collection badly, Menu says 6385.

**Comment by peppy** [comment] 2019-11-24 03:58
What CPU are you running on? That may be about right if you are on a low-end cpu and have other background tasks running.

**Comment by potato4444** [comment] 2019-11-24 04:03
Here is the output from `lscpu`

```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               61
Model name:          Intel(R) Pentium(R) CPU 3825U @ 1.90GHz
Stepping:            4
CPU MHz:             1435.962
CPU max MHz:         1900.0000
CPU min MHz:         500.0000
BogoMIPS:            3799.71
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            2048K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer xsave rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust erms invpcid rdseed intel_pt xsaveopt dtherm ida arat pln pts md_clear flush_l1d
```

**Comment by potato4444** [comment] 2019-11-24 04:07
I think it did take a while to search before, but it didn't usually block me from typing more input into the search box by freezing, or at least I don't think it did. It's one of those things you don't pay attention to until you have a reason to.

**Comment by ThePooN** [comment] 2019-11-24 09:33
Chiming in, as you're running on Wine. It has notably slower performance in song select on lower-end computers - it shouldn't be as bad though. It would definitely be interesting to know if you can reproduce that behavior on a Windows install.

**Comment by smoogipoo** [comment] 2019-12-04 02:46
Are you sorting/grouping beatmaps? Try setting them both to "Title" and seeing if you can replicate.

**Comment by potato4444** [comment] 2019-12-04 15:22
@smoogipoo Still freezes with both set to "By Title".

**Comment by FuLygon** [comment] 2019-12-05 04:08
i have similar problem as well, freeze when searching

**Comment by smoogipoo** [comment] 2019-12-05 04:12
Please provide the osu!.db file.

**Comment by FuLygon** [comment] 2019-12-05 04:19
here is my osu.db
[osu!.db.zip](https://github.com/ppy/osu-stable-issues/files/3925081/osu.db.zip)

**Comment by potato4444** [comment] 2019-12-05 09:59
Here is my `osu!.db` as well.
[osu!.db.zip](https://github.com/ppy/osu-stable-issues/files/3926165/osu.db.zip)

**Comment by smoogipoo** [comment] 2019-12-05 11:05
Can't reproduce with either of your db's. @FuLygon are you using wine?

**Comment by FuLygon** [comment] 2019-12-05 11:17
no im on windows 10 1909, using slow and old cpu Intel E8400 since i didnt have money for new mainboard yet, i did show the problem [here](https://youtu.be/Lqk7_ou22sk), the thing is this isn't happen before, i just notice them recently, gameplay is fine, no stutter and 0.6~1ms like before, only freeze in song selection screen

**Comment by FuLygon** [comment] 2019-12-05 11:42
welp these are my log files in case you askin
[Logs.zip](https://github.com/ppy/osu-stable-issues/files/3926627/Logs.zip)

**Comment by peppy** [comment] 2019-12-06 01:13
Based on the performance logs, there doesn't look to be any specific issue here. Your PC is just taking time to perform searches. This will be improved in lazer (by properly asyncing such flows) but is out of scope for stable.

If it is annoying, I'd suggest removing some beatmaps for now.

**Closed by peppy** 2019-12-06 01:13 UTC
Labels: will investigate
